### ISSUE TITLE
Captive Portal Mode

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#10]
When devices associate with POSM in an unconnected environment, DNS won't resolve, etc. POSM should provide a captive portal that redirects users to a landing page that will present a list of available local services.

See #hardware on Slack for a list of potential options (many of which use `dnsmasq` for DNS + DHCP).

**Comment by mojodna** [comment]
@JeremyGrosser did some research on this and determined that none of the options he looked at were particularly good fits for this. Can you elaborate?

**Comment by JeremyGrosser** [comment]
So as I understand it, our goals/requirements are:
A) Advertise a wifi SSID that phones can connect to and access services local to the posm box
B) HTTP connections should initially be redirected to a landing page
C) Provide an interface for admins to change the SSID and wifi password
D) If a wired connection to the internet is available, NAT and route wifi clients out to it

The assumption is that hostapd will take care of A. B and D will mostly be done by iptables, but a captive portal solution will be required to configure iptables dynamically and satisfy C.

Here are the open source tools I looked at, none of which seemed like a good fit.

ChilliSpot: Probably the most well known and widely deployed open source captive portal. Satisfies all requirements except for C. The code is some pretty crusty old Perl and would require us to run a RADIUS server on the device as well, adding complexity and another thing that can fail. This project is no longer maintained upstream and has been forked as CoovaChilli, which is even more complicated with support for 802.1X and tighter integration with OpenWRT.

WifiDog: Very much overkill for our use case, designed to manage hundreds of wireless gateways, requires both an access point daemon and a central management portal, which is PHP and PostgreSQL. Lots of moving parts, still doesn't satisfy C.

OpenWRT's UCI and corresponding LUCI web interface: Would easily handle the admin interface portion, but does not provide a traditional captive portal. It's built to run on OpenWRT, not Debian/Ubuntu. There are several bugs and forum posts discussing what it would take to port it, but as far as I can tell, nobody's actually done it before. https://forum.openwrt.org/viewtopic.php?id=33787 http://luci.subsignal.org/trac/ticket/248

NoCatSplash: A very simple captive portal, does provide an admin page but doesn't allow configuring the SSID and password from there. We might be able to modify it to add those fields. Uses a single daemon and some static html files, so it should be pretty robust. This is my favorite option so far.

**Comment by mojodna** [comment]
Ah, RADIUS. Yeah, let's stay away from that.

What are the commands (and config files) needed to set the SSID and password? I'm thinking that if we need

**Comment by dalekunce** [comment]
I know these seems like overkill but I really think the captive portal mode is the thing that will put it over the top and make it a true professional project. It will really makes things easier in the field for sure.

**Comment by jflemer-ndp** [comment]
Here's a possibly useful script for setting up "software ap" on Linux:
https://github.com/oblique/create_ap

**Comment by jflemer-ndp** [comment]
Have the basics committed here: https://github.com/AmericanRedCross/posm-build/commit/0bdeed3ff3f48bdfef7d65b3b4c003c47a05230d

This does:
 - AP mode
 - DHCP
 - DNS

Does not yet do:
 - NAT to wired network
 - "Captive Portaling" (no DNS trickery nor `divert` trickery)
 - Any web-management of the AP or Portal

**Comment by jflemer-ndp** [comment]
Implemented "Captive Portaling" by DNS wildcard and VHOSTs:
https://github.com/AmericanRedCross/posm-build/commit/59d739c08c37a16d1ec6f186776514e9f1e7a795

**Comment by mojodna** [comment]
Only a "cancel" option:

![image](https://cloud.githubusercontent.com/assets/45/12593412/dafd22d4-c425-11e5-8aeb-efee1da78a37.png)

Possibly because it’s a 403, but maybe not. OS X did the same, though clicking the red close button allowed it to stay connected.

“Captive Network Assistant” is the name of this iOS feature. It probes to see if it can connect to the internet.

Sample request:

```
192.168.6.75 - - [26/Jan/2016:11:55:05 -0800] "GET /hotspot-detect.html HTTP/1.0" 302 169 "-" "CaptiveNetworkSupport-325.10.1 wispr"
```

Previous path was `/library/test/success.html` (per https://grpugh.wordpress.com/2014/10/29/an-undocumented-change-to-captive-network-assistant-settings-in-os-x-10-10-yosemite/)

Should return a 200 and possibly the word "success."

More info on captive portal behavior: https://github.com/vtsatskin/FX-Captive-Portals-Design/blob/master/detection.md

(Android includes such a thing, but I couldn't quickly figure out the path.)

ChromeOS: http://www.chromium.org/chromium-os/chromiumos-design-docs/network-portal-detection

`/generate_204` - should return a 204.

Windows 7: http://blog.superuser.com/2011/05/16/windows-7-network-awareness/

Looking in `/var/log/nginx/access.log` will reveal paths as we have devices connect to the captive portal.

**Comment by jflemer-ndp** [comment]
Captive portal is captive.  See #32 for dealing with captive portal detection (and to what extent).
