### ISSUE TITLE
External Field Test Issue: Field papers - Batch uploading of snapshots

### ISSUE THREAD

**Issue by emilyhobson** [AmericanRedCross/posm#100]
[fp-web: Batch uploading of snapshots](https://github.com/fieldpapers/fieldpapers/issues/216)

**Comment by mojodna** [comment]
Can be done in the field while working with Drishtie.

**Comment by mojodna** [comment]
Successfully uploaded images can be deleted, failures should be dropped into a `failed/` directory.
