### ISSUE TITLE
fp-web: Export data grid (CSV) of snapshot ids corresponding to atlas pages

### ISSUE THREAD

**Issue by emilyhobson** [AmericanRedCross/posm#101]
[fp-web: Export data grid (CSV) of snapshot ids corresponding to atlas pages](https://github.com/fieldpapers/fieldpapers/issues/217)

**Comment by mojodna** [comment]
Can be done in the field alongside Drishtie

**Comment by mojodna** [comment]
Done in https://github.com/fieldpapers/fp-web/pull/31
