### ISSUE TITLE
Standalone scripts for network configuration changes

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#102]
We want standalone scripts to do the following things (both to change them immediately and to persist those changes):

- [x] set SSID
- [x] set WAP password
- [x] toggle open AP mode
- [x] switch between bridged + captive portal mode (network-only)
- [x] toggle nginx captive portal (equivalent of `a2ensite` / `a2dissite` for nginx)
- ...

It would also be nice to display some basic stats, so we'll need the ability to:

- [ ] list / count current network clients
- [ ] display WAN configuration (broken out or as JSON)
- ...

Some of these are trivial wrappers around somewhat arcane commands (namely `grep`ing `ifconfig` output, etc.), but having them as individual commands will be very helpful.

**Comment by hallahan** [comment]
Probably want to execute them in posm-admin
