### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by jharpster** [AmericanRedCross/posm#104]
Default install fails using the instructions at: https://github.com/AmericanRedCross/posm-build

![20160229_110717_001](https://cloud.githubusercontent.com/assets/224853/13405781/fabb02b6-ded4-11e5-9ed3-a274e077f6d8.jpeg)

**Comment by mojodna** [comment]
I can repro this w/o a LAN connection, though it forced me to manually configure the network (i.e. skipping it) earlier in the process.

@jharpster might your internet have dropped mid-way through the process?

**Comment by jharpster** [comment]
It is giving me some grief about the DHCP protocol. Will try to skip and move on.

**Comment by mojodna** [comment]
I'm not sure you'll be able to. The bootstrap requires a wired network connection (and an IP), so if DHCP is failing it won't be able to succeed.

**Comment by jharpster** [comment]
Yup, bad cable.

**Comment by mojodna** [comment]
Sorry, wrong issue.
