### ISSUE TITLE
/etc/tessera.conf.d

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#105]
I added the config directory to the carto bootstrap. It's part of my posm-admin branch.

https://github.com/AmericanRedCross/posm-build/commit/60e6a145c5bf32140c6701135ed233bfb6a1a4a6

I'm writing the tessera configuration script to write files to that directory in `posm-admin`. We need to have tessera properly read files in that dir.

**Comment by mojodna** [comment]
Done in https://github.com/AmericanRedCross/posm-build/commit/41787d9655559eac2371f3a386eef44a5ac89a64
