### ISSUE TITLE
Global Settings File /etc/posm.json 

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#106]
We have lots of settings in `posm-build` in bash files like `SETTINGS` and `SETTINGS.local`. This is out of reach from `posm-admin`, since they live in `/root`. Also, We have JS that needs to access these settings as well.

We need a JSON as well as bash settings file that is readable anywhere in the system.

**Comment by mojodna** [comment]
This will also be helpful for bash scripts, as `jq` can be used to pull stuff out and into variables:

```bash
fqdn=$(jq -r .posm_fqdn /etc/posm.json)
# fqdn=posm.local
```
