### ISSUE TITLE
Button up OSM Export Tool deployment

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#107]
Celery workers and Django are currently running in tmux sessions. They should be running out of upstart.

Also include appropriate documentation (upstream doesn't include deployment instructions).

**Comment by mojodna** [comment]
Upstart configs exist on ec2-52-32-62-7.us-west-2.compute.amazonaws.com but haven't been put into version control yet.

**Comment by mojodna** [comment]
These should be merged with @ranchodeluxe's https://github.com/ranchodeluxe/osm-export-ops

(We don't run Overpass, so we may need to do some minor refactoring on the Ansible playbooks.)

**Comment by mojodna** [comment]
`/etc/init/osm-export-tool2.conf`:
```
description     "osm-export-tool2 (gunicorn)"

start on (local-filesystems and net-device-up and runlevel [2345])
stop on shutdown


respawn
#respawn limit 5 60

pre-start script
    echo "[`date '+%c'`] Starting: osm-export-tool2" >> /var/log/osm-export-tool2.log
end script

pre-stop script
    echo "[`date '+%c'`] Stopping: osm-export-tool2" >> /var/log/osm-export-tool2.log
end script

exec start-stop-daemon \
		--start \
		--chdir /home/ubuntu/osm-export-tool2 \
		--chuid ubuntu \
		--make-pidfile \
		--pidfile /var/run/osm-export-tool2.pid \
                --exec /usr/local/bin/gunicorn -- core.wsgi:application --workers=3 --bind :8001 >> /var/log/osm-export-tool2.log 2>&1
```

`/etc/init/celery.conf`:
```
description     "celery"

start on (local-filesystems and net-device-up and runlevel [2345])
stop on shutdown

env DJANGO_SETTINGS_MODULE=core.settings.prod

respawn
#respawn limit 5 60

pre-start script
    echo "[`date '+%c'`] Starting: celery" >> /var/log/celery.log
end script

pre-stop script
    echo "[`date '+%c'`] Stopping: celery" >> /var/log/celery.log
end script

exec start-stop-daemon \
		--start \
		--chdir /home/ubuntu/osm-export-tool2 \
		--chuid ubuntu \
		--make-pidfile \
		--pidfile /var/run/celery.pid \
                --exec /usr/local/bin/celery -- -A core worker >> /var/log/celery.log 2>&1
```

`/etc/init/celery-beat.conf`:
```
description     "celery-beat"

start on (local-filesystems and net-device-up and runlevel [2345])
stop on shutdown

env DJANGO_SETTINGS_MODULE=core.settings.prod

respawn
#respawn limit 5 60

pre-start script
    echo "[`date '+%c'`] Starting: celery-beat-beat" >> /var/log/celery-beat.log
end script

pre-stop script
    echo "[`date '+%c'`] Stopping: celery-beat-beat" >> /var/log/celery-beat.log
end script

exec start-stop-daemon \
		--start \
		--chdir /home/ubuntu/osm-export-tool2 \
		--chuid ubuntu \
		--make-pidfile \
		--pidfile /var/run/celery-beat.pid \
                --exec /usr/local/bin/celery -- -A core beat >> /var/log/celery-beat.log 2>&1
```

**Comment by mojodna** [comment]
Also to fix (and split into its own issue): celery chews up memory, potentially because it's buffering `tl` output (I'm guessing this because it's the main difference between HOT's instance that has the potential to use memory). Options to fix after verifying that that's actually the issue: 

1. give `tl` a quiet mode (by default?) (hard)
2. fix buffering from subshells in https://github.com/AmericanRedCross/osm-export-tool2/blob/posm/utils/mbtiles.py#L63-L66

**Comment by mojodna** [comment]
`tl` now runs in quiet mode, so that will no longer be the source of memory leaks. If they're still occurring, let's look elsewhere.

**Comment by ranchodeluxe** [comment]
baseline is in place and some weeding done. still weeding to go -- https://github.com/ranchodeluxe/osm-export-ops/tree/posm

TODO:

0. do the upstart scripts for `celery` and `celerybeat`

0. figure out dependencies `nodejs`, `tl`, `tilelive-http`, `tilejson`

0. full-site walkthrough

**Comment by mojodna** [comment]
`nodejs`: https://github.com/AmericanRedCross/posm-build/blob/master/kickstart/scripts/nodejs-deploy.sh#L6-L10

Once that's done, the rest can be installed w/ `sudo npm install -g tl tilelive-http tilejson`

**Comment by ranchodeluxe** [comment]
this is ready to be tested by someone else other than me. I was able to get `postfix` to work by manually running `sudo dpkg-reconfigure postfix` after sshing into vagrant VM. 

I tried many different things to get this to provision automatically, but none of them worked. manual will have to be the workaround for now

**Comment by mojodna** [comment]
Cool, I'll take it.

**Comment by ranchodeluxe** [comment]
Turns out all my issues were that I have home class broadband and my ISP was blocking outgoing mail. When I had this working this morning I was at a coffee shop. 

Currently, a postfix install WITHOUT configuring it as an 'Internet Site' seems to work fine for sending emails. So please double check that assumption

After install I see this, which seems correct:

```bash
$ sudo lsof -i :25
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
master  21705 root   12u  IPv4  97323      0t0  TCP *:smtp (LISTEN)
master  21705 root   13u  IPv6  97324      0t0  TCP *:smtp (LISTEN)
```

**Comment by mojodna** [comment]
Sweet. I'll give the POSM functionality a run-through tomorrow and we can see about replacing the existing `export.posm.io` w/ an Ansible-provisioned instance.

**Comment by mojodna** [comment]
Ansible playbooks done in https://github.com/AmericanRedCross/osm-export-ops/pull/1

Still need to replace the existing instance.

**Comment by mojodna** [comment]
@dalekunce can you create a second instance (same type as the existing export.posm.io) that we can provision to replace it when you get a chance? i've been slack on asking for this since there's still #167 to deal with (but i'm doing that now).

**Comment by dalekunce** [comment]
@mojodna do you want to just nuke that box so I don't have to do anything or do you want a new box and transfer over the IP and stuff.

**Comment by mojodna** [comment]
@dalekunce a new box would be easier so I can start with a clean OS image.

**Comment by dalekunce** [comment]
@mojodna do you car about anything on the old box?

**Comment by mojodna** [comment]
Nope.
