### ISSUE TITLE
Set default map zoom & lat/lng for FP & Map Viewer

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#109]
Field Papers and the Map Viewer should have a default extent that makes sense with the data loaded in the deployment. 

To get this right, we need to find the center point and correct zoom to put the map viewer at. We should find the bbox of the data in the Render DB and figure this out from there. The following `sed` commands will help us set up the default center for field papers. A similar approach will work for replacing the link to the map viewer in `posm-local-home`.

```
sed -ri 's/(env PORT=)[[:digit:]]+/\15123/' /etc/init/fp-web.conf
sed -r 's!(env DEFAULT_CENTER=).*$!\1"15/-17.8086/30.9282"!' fp-web.upstart
```

**Comment by mojodna** [comment]
#87 should be initialized with the same source.

**Comment by mojodna** [comment]
```bash
lat=$(jq -r '(.bbox[1] + .bbox[3]) / 2' $manifest_path)
lng=$(jq -r '(.bbox[0] + .bbox[2]) / 2' $manifest_path)
zoom=15
```

**Comment by mojodna** [comment]
`scripts/root_change-fp-center.sh`:
```bash
#!/bin/sh

# Change DEFAULT_CENTER in fp-web's upstart
# intended to be run as root

if [ $(whoami) != "root" ]; then
  >&2 echo $0 is intended to run as root
  exit 1
fi

sed -ri "s/(env DEFAULT_CENTER=)\".+\"$/\1\"${1}\"/" /etc/init/fp-web.conf

service fp-web restart
```

Also needs a corresponding `sudoers` entry.

**Comment by hallahan** [comment]
Cool, this should also be outlined as a "UI Action". #31

**Comment by hallahan** [comment]
This should be done automatically in [tessera-fp-reset.js](https://github.com/AmericanRedCross/posm-admin/blob/master/scripts/tessera-fp-reset.js#L126-L151). 

Is there a way we can do this without having to modify `posm-local-home`? Seems like we are touching too many places here...

**Comment by hallahan** [comment]
The `sed` command you provided doesnt seem to work:

```
admin@posm:~/posm-admin/scripts$ sudo ./root_change-fp-center.sh 5/0.10/21.21
sed: -e expression #1, char 35: number option to `s' command may not be zero
```

Any idea what that means @mojodna ?

**Comment by hallahan** [comment]
Trying `sed` straight-up as root fails in the same way when doing this:

```
sed -ri "s/(env DEFAULT_CENTER=)\".+\"$/\1\"4/1.11/1.11\"/" /etc/init/fp-web.conf
```

**Comment by mojodna** [comment]
(Resolved-ish in Slack)

Original line was `env DEFAULT_CENTER=3/0.00/20.00` (without quoted center). This regex makes quotes optional in the source line:

```
"s/(env DEFAULT_CENTER=)\"?.+\"?$/\1\"4\/1.11\/1.11\"/"
```
