### ISSUE TITLE
HOT Exports does not include all selected files, email link broken

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#111]
I did a HOT Export here:

http://ec2-52-32-62-7.us-west-2.compute.amazonaws.com/en/exports/fd3199a9-876c-4d88-8780-3bc907d07526/

I specified:

PBF Format
OSM XML Format
MBTiles

Note that I specified both the default OSM basemap as well as the Esri Ortho by pasting the endpoint in the input box.

The tool claimed that it was done, but all it gave me was an OSM PBF file.

<img width="1075" alt="screenshot 2016-03-08 04 26 00" src="https://cloud.githubusercontent.com/assets/556367/13601572/eba1bc2c-e4e5-11e5-943b-85d88d804c6f.png">

Also, the link to the export in the email notification gives me a 404.

<img width="1134" alt="screenshot 2016-03-08 04 27 05" src="https://cloud.githubusercontent.com/assets/556367/13601585/0b083aa0-e4e6-11e5-91b5-b919fc102bca.png">

http://ec2-52-33-209-25.us-west-2.compute.amazonaws.com/exports/fd3199a9-876c-4d88-8780-3bc907d07526/

**Comment by hallahan** [comment]
Note that the hostname is incorrect. This linke works instead:

http://ec2-52-32-62-7.us-west-2.compute.amazonaws.com/en/exports/fd3199a9-876c-4d88-8780-3bc907d07526/

I'm not seeing a `tar.gz` of the full export anywhere?

**Comment by mojodna** [comment]
Hostname is fixed, thanks for catching that.

**Comment by mojodna** [comment]
Download list is fixed in https://github.com/AmericanRedCross/osm-export-tool2/commit/fbec3af71957194692e9974cee0d6f46b91ba5c0

Reloading http://ec2-52-32-62-7.us-west-2.compute.amazonaws.com/en/exports/fd3199a9-876c-4d88-8780-3bc907d07526/ will now display all available downloads.
