### ISSUE TITLE
Produce a fully-configured OS image that can be installed from an SD card or USB stick

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#12]
SD card would be preferable, as the NUC's BIOS includes an option to make it appear as a read-only device.

This potentially involves creating a minimal bootable image containing a tarball (of a prepared root fs) that is extracted onto the internal drive after initial partitioning and formatting. (If you had something else in mind, feel free to ignore this.)

A visual progress meter (as simple as `pv posm.tar.gz | tar ...`) would be a nice bonus for when a display is plugged in.

**Comment by mojodna** [comment]
See also http://askubuntu.com/questions/409607/how-to-create-a-customized-ubuntu-server-iso

**Comment by mojodna** [comment]
[Clonezilla Live](http://clonezilla.org/clonezilla-live.php) + a [scripted install](http://clonezilla.org/related-articles/012_Automated_USB_thumb_drive_using_Custom/Automated_USB_thumb_drive_using_Custom.html) 

See [Save disk image](http://clonezilla.org/show-live-doc-content.php?topic=clonezilla-live/doc/01_Save_disk_image) for more info.

It may even be possible to do this from a VM (with the side-effect of installing a couple of extra virt-related packages).

**Comment by mojodna** [comment]
https://www.howtoforge.com/converting-a-vmware-image-to-a-physical-machine-p2

**Comment by mojodna** [comment]
http://clonezilla.org/fine-print-live-doc.php?path=clonezilla-live/doc/99_Misc/00_live-boot-parameters.doc

**Comment by mojodna** [comment]
http://allthatnetwork.blogspot.com/2012/10/clonezilla-ocs-sr-options.html

**Comment by mojodna** [comment]
`EFI/boot/grub.cfg`:

```
linux /live/vmlinuz boot=live union=overlay username=user hostname=xenial config components  noswap edd=on nomodeset nodmraid noeject locales=en_US.UTF-8 keyboard-layouts=NONE ocs_live_run="ocs-live-restore" ocs_live_extra_param="-scr --no-restore-mbr --ius -p true restoredisk 20160526-west-africa sda" ocs_postrun0="/lib/live/mount/medium/live/update-efi.sh" ocs_postrun1="poweroff" ocs_live_batch=yes acpi=off irqpoll noapic noapm nodma nomce nolapic nosmp ip= net.ifnames=0 nomodeset vga=normal nosplash
```

`live/update-efi.sh`:

```bash
#!/bin/sh

efibootmgr -c -l '\EFI\ubuntu\grubx64.efi' -L POSM
```

**Comment by mojodna** [comment]
## Installation / Updating

1. Download http://posm.s3.amazonaws.com/dist/POSM-20160526-west-africa.tar
2. Using 7-Zip (http://www.7-zip.org/) or another utility that can decompress TAR archives, extract POSM-20160526-west-africa.tar to an empty directory
3. Copy the contents of the directory to a fresh USB stick (the partition table needs to be GPT, but I think that's the default now; it's possible to erase and create such partitions using Disk Utility on OS X, not sure about Windows)
4. Plug a keyboard, monitor, and the prepared USB stick into the POSM being updated and turn it on.
5. When the NUC logo shows up, hit F10 to enter the boot menu.
6. Select UEFI : USB : <USB stick info> : ...

At this point, it should boot into a blue menu with a single option: POSM 20160526-west-africa

You can either hit enter or wait 30 seconds for it to boot. It will display a bunch of log output and cycle through a few screens as it copies the OS image onto the POSM. When it's done, it will shut down automatically.

To complete the installation, remove the USB stick and power the POSM back on. You should see a login prompt, at which point you can disconnect the monitor and keyboard. There will be a "POSM" wireless network that you can connect to (password: "awesomeposm") and use http://posm.io/

Data for Guinea, Sierra Leone, and Liberia as of 5/25/16 (courtesy of the Geofabrik extracts) has been pre-provisioned, meaning that the local OSM instance includes data and that map tiles may be rendered (and Field Papers created). To browse around the local OSM instance, go to http://osm.posm.io/ while connected to the OSM wifi network.

Should you need the original OSM PBF, it's in `/opt/data/aoi/west-africa/osm/west-africa-latest.pbf` (`ssh root@posm.io`, password: `posm`).

With a USB 3.0 flash drive, this process takes about 10 minutes.

**Comment by mojodna** [comment]
https://github.com/AmericanRedCross/posm-build/pull/48/files#diff-acd9d7c1d973910deee139847f058a0dL56 totally eliminated the `update-efi.sh` work-around. Clonezilla was confused because there were multiple bootable partitions.

This means that an out-of-the-box Clonezilla restore image works, although it does require some user intervention to confirm intent.

**Comment by mojodna** [comment]
@dalekunce was able to successfully install this.

I can create additional Clonezilla images on an ad-hoc basis (and will once the components have settled).

In the meantime, I'm opening a backlog issue for a Live USB image.

**Comment by danbjoseph** [comment]
@emilyeros wasn't seeing the described options in the boot menu (see below pic). when this process is documented in a readme or wherever, please include as much detail as possible. 
not sure what was causing her problem. but for example, it's not immediately apparent how to set the partition scheme (under options on the partition tab) and then recognizing that "GUID partition scheme" is "GPT" (disk utility doesn't spell out the acronym).
![img_1419](https://cloud.githubusercontent.com/assets/4806884/15805364/ecc2de32-2af5-11e6-92d0-91caa9ecff22.jpg)
