### ISSUE TITLE
OMK -> POSM

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#125]
Currently, OMK gets data into POSM by iD as the middle man in a validation step. In Huaquillas, we found that the size of the OSM aggregations in vivo is too large for iD. 

We ended up just putting all of the OMK edits as-is into POSM. Further edits can be done in the POSM iD. We did not find that to be a problem.

This does mean, however, that we still need to be able to view OSM OMK edits from OpenMapKit Server on a map. Further input will be needed regarding that.

**Comment by emilyhobson** [comment]
@hallahan Can you self-assign if this is yours?

**Comment by hallahan** [comment]
Once I complete this, I need to resolve #99

**Comment by hallahan** [comment]
We have an Epic in the OpenMapKit Server repo tracking this issue. I'm going to document progress in there, since I can break things down into smaller issues with smaller LOEs within the larger epic for management and book keeping.

https://github.com/AmericanRedCross/OpenMapKitServer/issues/55
