### ISSUE TITLE
Changeset Replay Tool Test VMs

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#126]
We need 2 VMs, one as the `source` OSM API and another as the `upstream` OSM API. These should be prepped with Huaquillas data, ready to be used for development of the `changeset-replay-tool`.

**Comment by dalekunce** [comment]
do I need to spin these up as EC2 instances? @hallahan @mojodna

**Comment by hallahan** [comment]
No, VirtualBox VMs will be fine.

**Comment by mojodna** [comment]
This is part of dev / testing of the changeset replay tool and varies according to individual workflows.

For my part, I intend to run the same instance of openstreetmap-website on my Mac w/ different `DATABASE_URL`s set.
