### ISSUE TITLE
Custom osm2pgsql style w/ extra attributes

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#129]
We had one at one point but it got dropped along the way. `osm2pgsql` is still run with `--extra-attributes`, but that only works if there are corresponding entries in the style file. We want this in order to expose the version and user (id) properties of given entities so we can treat locally edited data differently in posm-carto.

**Comment by mojodna** [comment]
Higher priority if @almccon needs it for posm-carto work.

**Comment by almccon** [comment]
Should I update my local test-rendering databases for posm-carto? Or is the osm2pgsql style the same?

**Comment by mojodna** [comment]
It's the same, no need to change anything.
