### ISSUE TITLE
Configure nginx as a reverse proxy

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#13]
We want a single point of entry for all services running on the device. We should document the ports in use in a README.

**Comment by jflemer-ndp** [comment]
Does anyone care what (internal) port things run on, or is it up to me to configure and proxy them?  Initially, I'll pick ports an document them as I go (until someone complains).

**Comment by hallahan** [comment]
I'd like to keep `3210` for OpenMapKit Server, just because that's what I'm used to.

**Comment by jflemer-ndp** [comment]
| URI | Service | Proxy URL | Port |
| --- | --- | --- | --- |
| `/tl` | tessera | `http://127.0.0.1:{{tessera_port}}` | 8082 |
| `/fp-tiler` | FP Tiler | `http://127.0.0.1:{{fp_tiler_port}}/fp-tiler` | 8080 |
| `/fp-tasks` | FP Tasks | `http://127.0.0.1:{{fp_tasks_port}}/fp-tasks` | 8081 |
| `/omk` | OMK Server | `http://127.0.0.1:{{omk_server_port}}` | 3210 |

**Comment by jflemer-ndp** [comment]
Updated the main posm-build readme with ports etc.
https://github.com/AmericanRedCross/posm-build/blob/master/README.md

**Comment by hallahan** [comment]
Could we have a `/public` NGINX endpoint?

**Comment by jflemer-ndp** [comment]
Yes, we'll definitely need to serve quite a bit of static content.
