### ISSUE TITLE
Experiment with using diff updates to sync the rendering database

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#135]
Periodic wholesale re-syncing is fine for now (especially considering the level of use that `posm-carto` saw in Ecuador), but long-term flowing diff updates would allow the basemap to be fully in sync w/ edits.

**Comment by hallahan** [comment]
Agreed. That would be a good next step. I think we can be satisfied with the cron job for now?

http://wiki.openstreetmap.org/wiki/Minutely_Mapnik

**Comment by mojodna** [comment]
Yes, for sure.

**Comment by hallahan** [comment]
The cron job is causing problems. For example, if I'm doing a FieldPapers -> OMK Atlas deployment and cutting posm carto tiles, if the cron job happens and the render db gets dropped, it fails.

I think I'm going to disable the cron job and just have the update be explicit in POSM Admin for now.

<img width="1414" alt="screenshot 2016-04-26 08 46 08" src="https://cloud.githubusercontent.com/assets/556367/14824633/79c5278e-0b8b-11e6-8f6e-b393f3ea4a77.png">
