### ISSUE TITLE
Disable FP user logins

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#137]
Since accounts can't be confirmed (it sends email), this is functionally useless.

**Comment by ranchodeluxe** [comment]
Is this about removing login or just disabling sending confirmation emails? The dev site works fine without a new user confirming their account ( I could be missing something ).

Disabling `Devise` from sending emails was a couple lines of code
https://github.com/fieldpapers/fp-web/compare/137_disable_user_logins?expand=1

**Comment by mojodna** [comment]
I was originally thinking that it was about adding a feature flag that would hide the "sign up / log in" nav bar items, but it might actually be better to disable confirmation emails (and the associated requirement that the links therein be clicked). Your call.

Dev is special, I suspect. It doesn't send emails, for example, though not requiring confirmation is new to me.

**Comment by mojodna** [comment]
https://github.com/fieldpapers/fp-web/pull/30
