### ISSUE TITLE
Create a POSM integration/test Docker image

### ISSUE THREAD

**Issue by jflemer-ndp** [AmericanRedCross/posm#14]
Make a docker image available for POSM dev integration and test using the build scripts (to keep from having to build from scratch so often).

**Comment by mojodna** [comment]
Docker image or VM? (Wondering due to confusion associated with running multiple executables in the same Docker container as well as complications around modifying a Docker container's filesystem.)

[Packer](https://packer.io/) might be helpful here, especially if it's possible to use a provisioner that uses kickstart (not everyone has a PXE environment ;-).

**Comment by jflemer-ndp** [comment]
Was thinking a docker image to "bash" into. But maybe a VM (OVA) would be better. I can do either or both.

**Comment by mojodna** [comment]
VM seems better, as it can also be configured to run services.

**Comment by jflemer-ndp** [comment]
working on an ova ...

**Comment by mojodna** [comment]
ETA: 9 months then?

**Comment by jflemer-ndp** [comment]
Lol.  Can someone upload the resulting image to S3 or somewhere?

**Comment by mojodna** [comment]
Yup.

@dalekunce is there an S3 bucket we should be using for this kind of thing? (Actually, we might want to create a new one since we'll be stashing other stuff there as part of the device deployment process.)

**Comment by jflemer-ndp** [comment]
OVA export command for my reference:
```
ovftool --diskMode=sparse --chunkSize=200mb --name=posm --targetType=OVA vi://root@vmhost/posm /tmp/posm.ova
```

**Comment by jflemer-ndp** [comment]
Uploaded first test OVA to http://posm.s3.amazonaws.com/ova/posm-v0.2-0.ova

**Comment by mojodna** [comment]
USB installer / VM snapshots seem to have covered the main pain points here. It's still painful (and we still need #12 for quick, reliable hardware provisioning), but it could be worse.
