### ISSUE TITLE
Periodic backups

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#141]
If disconnected, just the databases (Postgres: `osm`, MySQL: `fieldpapers_production`) should be backed up and stored somewhere.

If an SD card is connected, copy data to that:

* OMK forms
* OMK submissions
* database backups
* FP atlases
* FP snapshots
* OSM PBF (will match the `osm` backup, but is more convenient in this form)

This would be exposed as a button in posm-admin, I imagine.

**Comment by dalekunce** [comment]
Would be great to use either a SDCard or USB stick and do something in the POSM Admin

**Comment by mojodna** [comment]
External storage is tracked in #150; this is just about doing the backups.

**Comment by hallahan** [comment]
We also need to restore from a backup.

**Comment by hallahan** [comment]
Might be a good task for @danielduhh . This should be in `posm-admin`.

**Comment by mojodna** [comment]
Let's drop writing directly to external storage from the POSM and instead ensure that the backup directory is exposed as a file share, since we already have that mechanism and it's more flexible when laptops are attached.

The relevant Samba configuration is in https://github.com/AmericanRedCross/posm-build/blob/master/kickstart/etc/smb.conf You'll want to make them read-only (the existing fileshares are globally read/write).

**Comment by hallahan** [comment]
Done
