### ISSUE TITLE
GitHub admin tasks

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#153]
To make discoverability of POSM-related code easier.

**Comment by dalekunce** [comment]
does this have an action for me?

**Comment by mojodna** [comment]
It will soon.

**Comment by mojodna** [comment]
- [ ] Create AmericanRedCross/posm-relay-tool w/ appropriate privs
- [ ] Change default branch on https://github.com/AmericanRedCross/openstreetmap-website to `posm`
- [ ] Change default branch on https://github.com/AmericanRedCross/id to `posm`
- [ ] Change default branch on https://github.com/AmericanRedCross/osm-export-tool2 to `posm`

**Comment by dalekunce** [comment]
https://github.com/AmericanRedCross/posm-relay-tool

Done.

cc @mojodna

**Comment by mojodna** [comment]
Dammit, I meant posm-replay-tool.  Mind renaming?

**Comment by dalekunce** [comment]
done
