### ISSUE TITLE
Make POSM HOT Export Tool instance more real

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#154]
Give it an actual hostname and...stuff.

**Comment by dalekunce** [comment]
export.posm.io ??

**Comment by mojodna** [comment]
Perfect. Can you map it to the EIP belonging to the instance?

**Comment by mojodna** [comment]
Once that's done, I'll update the Django config.

**Comment by mojodna** [comment]
@dalekunce ping re: mapping `export.posm.io` to the Export EIP instance (http://ec2-52-32-62-7.us-west-2.compute.amazonaws.com/)

**Comment by mojodna** [comment]
Django + Nginx configuration updated (Nginx is necessary for Python Social Auth to know what hostname to use as a `redirect_uri`). It's gotten "real".
