### ISSUE TITLE
Field Papers -> posm-admin Webhook

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#155]
posm-admin is going to have a REST endpoint that can be hit with the URL to a Field Papers `map.geojson`. This will tell posm-admin that it's time to cook OSM XML and MBTiles for OMK.

When a FP atlas is completed, it needs to hit that end point.

**Comment by mojodna** [comment]
Field Papers end of the web hook implemented in https://github.com/fieldpapers/fp-web/pull/27

@hallahan is there an endpoint in posm-admin or OMK server yet?

/cc @ranchodeluxe

**Comment by hallahan** [comment]
Yes.

The route: https://github.com/AmericanRedCross/posm-admin/blob/jekyll/api/routes.js#L57-L59

The controller:

**Comment by hallahan** [comment]
You can `GET` or `POST` to `/posm-admin/atlas-deploy` with a `url` to the `http://posm.io/fp/atlases/<slug>.geojson`

**Comment by hallahan** [comment]
This should be inches away from being done.

**Comment by mojodna** [comment]
Kicking over to @hallahan to coordinate integration w/ posm-admin.

**Comment by hallahan** [comment]
Completed via https://github.com/AmericanRedCross/posm-admin/pull/4
