### ISSUE TITLE
[posm-build] no project.xml - tessera / mapnik fails

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#157]
We're getting a strange problem in `posm-build` where the fonts don't download when deploying carto.

```
curl: (56) Recv failure: Connection timed out
make: *** [fonts/unifont-Medium.ttf] Error 56
```

After install, this is resolved by:

```
sudo -u gis -i
cd /opt/gis/posm-carto
make project.xml
exit
```

**Comment by mojodna** [comment]
Fixed by https://github.com/AmericanRedCross/posm-build/pull/41 and https://github.com/AmericanRedCross/posm-carto/commit/ec91cd9c1c0ca1d73b7d28361862a5496cd1bb31
