### ISSUE TITLE
Create a simplistic OSM style

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#16]
Using `osm2pgsql`'s hstore schema. Doesn't need to be fancy, just needs to prove the point.

**Comment by mojodna** [comment]
Needed for #15

**Comment by dalekunce** [comment]
Eventually I think we are going to want to have a Field Papers style. Something that renders super well on B&W prints.

**Comment by mojodna** [comment]
And with big labels.

**Comment by mojodna** [comment]
![image](https://cloud.githubusercontent.com/assets/45/12014753/1b7d7986-ace7-11e5-82b7-3e72219ce2f7.png)

Temporarily here until we have an @AmericanRedCross repo for it: https://github.com/mojodna/carto-posm-simple

**Comment by dalekunce** [comment]
https://github.com/AmericanRedCross/posm-carto

**Comment by mojodna** [comment]
Yay!
