### ISSUE TITLE
[posm-admin] Offline Fonts

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#163]
Fonts are not working offline yet. We need this to be a static asset served from the project itself.

<img width="1412" alt="screenshot 2016-05-03 15 57 12" src="https://cloud.githubusercontent.com/assets/556367/14996425/e956e9ea-1147-11e6-924e-fefd61bf672f.png">

<img width="245" alt="screenshot 2016-05-03 15 56 31" src="https://cloud.githubusercontent.com/assets/556367/14996427/ec2129f6-1147-11e6-8265-aff870e20185.png">

**Comment by hallahan** [comment]
cc/ @danielduhh

**Comment by danielduhh** [comment]
@hallahan on it

**Comment by hallahan** [comment]
Done via https://github.com/AmericanRedCross/posm-admin/commit/ee39f2bed7b81143aac4f6576eec4c8308aad4d4
