### ISSUE TITLE
posm export doesn't include haiti

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/posm#167]
HOT export includes haiti
POSM export doesn't include haiti.

haiti is important can we whitelist it please.

**Comment by mojodna** [comment]
Weird! The restrictions should be exactly the same (unless they've manually modified the restricted areas). Since we're using Overpass.de (and not maintaining our own mirror at this point), we can remove the restrictions entirely.

**Comment by dalekunce** [comment]
yeah let's remove the restrictions globally.

**Comment by mojodna** [comment]
Restrictions removed in an ad-hoc way so far (though the boundaries for regions remain). Still TODO: create a database migration that drops the boundaries and replaces them with a single one for the whole world.
