### ISSUE TITLE
OSM Data and CLI Tool Exploration

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#17]
# OSM Data Sources

[OSM 0.6 Editing API](http://wiki.openstreetmap.org/wiki/API_v0.6)
* Up to date API of truth
* limited data request size
* may block a requester that asks for too much
* the authoritative place edits are submitted to

[Overpass API](http://wiki.openstreetmap.org/wiki/Overpass_API)
* Not limiting download size like Editing API
* allows sophisticated queries
* good for custom extracts
* up to date within 5 mins
* large downloads are acceptible
* __most likely our preferred option__

[Geofabrik](http://download.geofabrik.de/)
* provides daily OSM extracts
* continent, country, state level granularities
* up to date within a day
* easy to update to minute with osmupdate

[Mapzen Metro Extracts](https://mapzen.com/data/metro-extracts)
* provides weekly OSM extracts
* city / region level granularities
* up to date within week
* also updatable with osmupdate

[Planet File](http://planet.openstreetmap.org/)
* de-facto source for entire planet
* updated weekly
* provides daily, hourly, minutely changesets
* occasionally goes down

Fortunately, all of these sources can provide OSM data in the same format, and we will work with
the provided OSM files in the same way regardless.

# Osmosis

[Osmosis](http://wiki.openstreetmap.org/wiki/Osmosis) is the "swiss army" command line tool for manipulating OSM data. It has the most functionality, but it is less performant than other options.

Extract a bbox from a larger OSM file:

	osmosis --read-pbf sacramento_california2015-12-12.osm.pbf --bounding-box top=38.660783 left=-121.380301 bottom=38.643691 right=-121.349831 --write-xml file="arcade.osm"

Timing making an arcade creek extract from Metro Extract of San Francisco Bay Area to Arcade Creek, Sacramento:

	time osmosis --read-pbf san-francisco-bay_california2015-12-12.osm.pbf --bounding-box top=38.660783 left=-121.380301 bottom=38.643691 right=-121.349831 --write-xml file="arcade.osm"

This is starting to take a little bit of time...

	real	0m11.610s
	user	0m30.022s
	sys	0m1.607s

# osmconvert

Looking at doing the same exact thing in [osmconvert](http://wiki.openstreetmap.org/wiki/Osmconvert). Osmconvert is a tool used by 
[Geofabrik](http://download.geofabrik.de/) to create extracts and handle updating.

	time osmconvert san-francisco-bay_california2015-12-12.osm.pbf -b=-121.380301,38.643691,-121.349831,38.660783 -o=arcade.osm

Looks like `osmconvert` is 10x faster for this operation...

	real	0m1.923s
	user	0m1.517s
	sys	0m0.392s

Let's try doing the same thing for the entire state of California...

	time osmconvert california2015-12-15.osm.pbf -b=-121.380301,38.643691,-121.349831,38.660783 -o=arcade.osm

	real	0m7.575s
	user	0m6.917s
	sys	0m0.585s

That's pretty fast! Let's see how well `osmosis` does...

	real	0m26.307s
	user	0m29.596s
	sys	0m1.017s

As you can see, `osmconvert` is drastically faster.

`osmconvert` seems to be so fast for cutting out extracts, maybe I can get my neighborhood from the entire planet file in a timely mannor?

	time osmconvert planet-151207.osm.pbf -b=-121.380301,38.643691,-121.349831,38.660783 -o=arcade.osm
	
	real	7m31.240s
	user	7m14.113s
	sys	0m12.759s

That's pretty amazing!

# Overpass API

Though [Overpass API](http://wiki.openstreetmap.org/wiki/Overpass_API) is a remote service, the elegance of it's query language lets you ask all kinds of questions. With a simple query, you can get an extract of an area as well. Here is a query getting all of the data from the bounding box of my neighborhood, Arcade Creek.

	(
	  // Overpass does bbox in a Lat/Lng arrangement.
	  relation(38.643691,-121.380301,38.660783,-121.349831);
	  way(38.643691,-121.380301,38.660783,-121.349831);
	  node(38.643691,-121.380301,38.660783,-121.349831);
	);
	out meta;
	>;
	out meta qt;

We can easily make that query into a GET request from the Overpass API (as well as several mirrors).

	time wget "http://overpass-api.de/api/interpreter?data=(relation(38.643691,-121.380301,38.660783,-121.349831);way(38.643691,-121.380301,38.660783,-121.349831);node(38.643691,-121.380301,38.660783,-121.349831););out%20meta;>;out%20meta%20qt;" -O arcade.osm

	real	0m24.869s
	user	0m0.022s
	sys	0m0.

	File Size: 2.68M

This option seems pretty nice, and it definitely takes less long than extracting from a planet file.
Let's take a look at how long it takes to get San Francisco...

	time wget "http://overpass-api.de/api/interpreter?data=(relation(37.671864,-122.574463,37.843410,-122.350616);way(37.671864,-122.574463,37.843410,-122.350616);node(37.671864,-122.574463,37.843410,-122.350616););out%20meta;>;out%20meta%20qt;" -O sf.osm

	real	2m57.180s
	user	0m2.239s
	sys	0m11.024s

	File Size: 690.43M

Now things are taking a little while longer... Nonetheless, SF is a lot of data. 
A major advantage of Overpass is that we do not have to maintain an up to date planet file
and apply changesets. Also, it is still faster than extracting SF from a planet file:

	time osmconvert planet-151207.osm.pbf -b=-122.574463,37.671864,-122.350616,37.843410 -o=sf.osm

	real	7m18.810s
	user	7m1.714s
	sys	0m12.912s

Interesting. It looks like the size of the excerpt can vary, yet it takes a consistent amount to time to do it
with a planet file and `osmconvert`.

# osmupdate

[`osmupdate`](http://wiki.openstreetmap.org/wiki/Osmupdate) looks at an OSM file (XML or PBF), fetches changesets from http://planet.openstreetmap.org/replication
and then applies those `osc` changesets to the file. Since it looks at the planet for changesets,
it is applying minutelys to that source file.

Here we are updating an extract of Sacramento from yesterday:

	time osmupdate sacramento_california2015-12-12.osm.pbf sacramento_california_updated.pbf

	real	3m24.981s
	user	0m53.067s
	sys	0m5.484s

While the tool is running, there is a temporary working directory. You can see the minutelys in there:

```
ls osmupdate_temp
temp.8			temp.m001705612.osc.gz	temp.m001705620.txt	temp.m001705629.osc.gz	temp.m001705637.txt	temp.m001705646.osc.gz	temp.m001705654.txt	temp.m001705663.osc.gz
temp.h000028564.osc.gz	temp.m001705612.txt	temp.m001705621.osc.gz	temp.m001705629.txt	temp.m001705638.osc.gz	temp.m001705646.txt	temp.m001705655.osc.gz	temp.m001705663.txt
temp.h000028564.txt	temp.m001705613.osc.gz	temp.m001705621.txt	temp.m001705630.osc.gz	temp.m001705638.txt	temp.m001705647.osc.gz	temp.m001705655.txt	temp.m001705664.osc.gz
temp.h000028565.osc.gz	temp.m001705613.txt	temp.m001705622.osc.gz	temp.m001705630.txt	temp.m001705639.osc.gz	temp.m001705647.txt	temp.m001705656.osc.gz	temp.m001705664.txt
temp.h000028565.txt	temp.m001705614.osc.gz	temp.m001705622.txt	temp.m001705631.osc.gz	temp.m001705639.txt	temp.m001705648.osc.gz	temp.m001705656.txt	temp.m001705665.osc.gz
temp.h000028566.osc.gz	temp.m001705614.txt	temp.m001705623.osc.gz	temp.m001705631.txt	temp.m001705640.osc.gz	temp.m001705648.txt	temp.m001705657.osc.gz	temp.m001705665.txt
temp.h000028566.txt	temp.m001705615.osc.gz	temp.m001705623.txt	temp.m001705632.osc.gz	temp.m001705640.txt	temp.m001705649.osc.gz	temp.m001705657.txt	temp.m001705666.osc.gz
temp.h000028567.osc.gz	temp.m001705615.txt	temp.m001705624.osc.gz	temp.m001705632.txt	temp.m001705641.osc.gz	temp.m001705649.txt	temp.m001705658.osc.gz	temp.m001705666.txt
temp.h000028567.txt	temp.m001705616.osc.gz	temp.m001705624.txt	temp.m001705633.osc.gz	temp.m001705641.txt	temp.m001705650.osc.gz	temp.m001705658.txt	temp.m001705667.osc.gz
temp.h000028568.osc.gz	temp.m001705616.txt	temp.m001705625.osc.gz	temp.m001705633.txt	temp.m001705642.osc.gz	temp.m001705650.txt	temp.m001705659.osc.gz	temp.m001705667.txt
temp.h000028568.txt	temp.m001705617.osc.gz	temp.m001705625.txt	temp.m001705634.osc.gz	temp.m001705642.txt	temp.m001705651.osc.gz	temp.m001705659.txt	temp.m001705668.osc.gz
temp.h000028569.osc.gz	temp.m001705617.txt	temp.m001705626.osc.gz	temp.m001705634.txt	temp.m001705643.osc.gz	temp.m001705651.txt	temp.m001705660.osc.gz
temp.m001705609.txt	temp.m001705618.osc.gz	temp.m001705626.txt	temp.m001705635.osc.gz	temp.m001705643.txt	temp.m001705652.osc.gz	temp.m001705660.txt
temp.m001705610.osc.gz	temp.m001705618.txt	temp.m001705627.osc.gz	temp.m001705635.txt	temp.m001705644.osc.gz	temp.m001705652.txt	temp.m001705661.osc.gz
temp.m001705610.txt	temp.m001705619.osc.gz	temp.m001705627.txt	temp.m001705636.osc.gz	temp.m001705644.txt	temp.m001705653.osc.gz	temp.m001705661.txt
temp.m001705611.osc.gz	temp.m001705619.txt	temp.m001705628.osc.gz	temp.m001705636.txt	temp.m001705645.osc.gz	temp.m001705653.txt	temp.m001705662.osc.gz
temp.m001705611.txt	temp.m001705620.osc.gz	temp.m001705628.txt	temp.m001705637.osc.gz	temp.m001705645.txt	temp.m001705654.osc.gz	temp.m001705662.txt
```

This applied all of the minutelys, so you're going to see that output dataset have geometries
external of the extent of the original dataset.

That's not what we want, because it creates a much larger file than our original.

	du -h sacramento_california2015-12-12.osm.pbf
	9.2M	sacramento_california2015-12-12.osm.pbf

	du -h sacramento_california_updated.pbf
 	95M		sacramento_california_updated.pbf

You can pretty easily clip the changeset merge to a bounding box.

![Clipping updates to this bbox](https://cloud.githubusercontent.com/assets/556367/11856051/e446089e-a402-11e5-8518-a94bcd305802.png)

	time osmupdate sacramento_california2015-12-12.osm.pbf sacramento_california_updated2.pbf -b=-121.647491,38.437993,-121.251297,38.696229

	real	2m39.543s
	user	0m46.180s
	sys		0m4.753s

It turns out that this output is smaller than the source file, because it cuts the total result by the bounding box.

	du -h sacramento_california_updated2.pbf
	3.5M	sacramento_california_updated2.pbf

![Sacramento Update Clipped in JOSM](https://cloud.githubusercontent.com/assets/556367/11856068/0665eff2-a403-11e5-884f-0af42312004b.png)

Overall, you can see that this sort of operation takes minues, which is significantly longer than it would be to just download a fresh dataset.

# Changesets

A second aspect to the workflow that we need to evaluate are changesets. We need to know how to apply new data on OSM files that we currently have. That new data needs to come from two places:

1. We need to apply changesets from the master OSM dataset that apply to our area of interest.
2. We need to apply changesets from OpenMapKit to our AOI OSM extract.

For data in OpenMapKit, we also need to account for negative IDs and colliding negative IDs from different changesets.

Note that there are two formats that we keep track of changes. There is the [JSOM file format](http://wiki.openstreetmap.org/wiki/JOSM_file_format), and this is what OMK uses. There is also the [OSC](http://wiki.openstreetmap.org/wiki/OsmChange) format that iD as well as [OSM Planet Diffs](http://wiki.openstreetmap.org/wiki/Planet.osm/diffs). JOSM can open OSC files and work with them in the same way as regular OSM files. It might be wise to revamp OpenMapKit Android's XML writer to write OSC format rather than JSOM OSM format.

Here is a basic OSC from a building that I created in iD:

	<osmChange version="0.6" generator="iD">
		<create>
			<node id="-1" lon="-121.41239939351759" lat="38.64028352633861" version="0" changeset="35978898"/>
			<node id="-4" lon="-121.41235653985323" lat="38.64028306144678" version="0" changeset="35978898"/>
			<node id="-7" lon="-121.4123577302328" lat="38.64025005412025" version="0" changeset="35978898"/>
			<node id="-10" lon="-121.41239998870735" lat="38.64025051901229" version="0" changeset="35978898"/>
			<way id="-1" version="0" changeset="35978898">
				<nd ref="-1"/>
				<nd ref="-4"/>
				<nd ref="-7"/>
				<nd ref="-10"/>
				<nd ref="-1"/>
				<tag k="building" v="shed"/>
			</way>
		</create>
		<modify/>
		<delete if-unused="true"/>
	</osmChange>

You can see that OSC is similar to the JOSM format in that new elements get a negative ID. Looking at a [planet minutely](http://planet.openstreetmap.org/replication/minute/001/704/743.osc.gz),
these IDs are positive, since they have already been added to the master OSM dataset.

OSC files have `<create>`, `<modify>`, `<delete>` blocks. The referential integrity of negative IDs only need to be consistent within a single change block. This means OMK Server shouldn’t have to rewrite negative IDs. I do notice that iD doesnt actually maintain unique negative IDs with a changeset as a whole always. In fact, 
within a `<create>` block, iD doesnt maintain unique IDs across nodes, ways, relations. Just unique for a given element type.

Take a look at a [larger `osc` file created by iD](https://www.dropbox.com/s/33itix0sy15j1fj/larger-osc.osc?dl=0).

As a takeaway, the [OsmChange wiki](http://wiki.openstreetmap.org/wiki/OsmChange) states that:

>The upload API call supports placeholders - in fact, all id attributes in create elements are treated as placeholders whether negative or not. However, you should stick to negative numbers to ensure that placeholder IDs do not clash with any other IDs in the OsmChange document.

---

I spent some time doing a survey in my neighborhood, both with buildings and POIs. This was done in AmigoCloud, and the data was then exported into a Shapefile, and then imported into JOSM and saved to OSM XML format. I had to do a fair amount of data cleaning, but here is some data we can use to see a larger JOSM edit file.

[Buildings](https://www.dropbox.com/s/eki5amae5rmac99/buildings.osm?dl=0)

[Nodes](https://www.dropbox.com/s/uroyy484e0ux9u1/nodes.osm?dl=0)

Note that these two files have negative IDs, and the IDs __DO NOT__ collide. We cannot always expect this luxury, because we will be getting changesets from different places (different phones). The ida of these negative IDs is that they must be unique within a single document, so when we merge documents, the merging action should reassign IDs.

## Creating Changesets from OSM and JSOM OSM Files

To define an update, it seems like we really want that data to be in `osc` format. We can easily turn any OSM file into an osc changeset. This works the same for JOSM OSM as well as standard OSM files.

Changesets are meant to be applied to the OSM Editing REST API to change the
master data set. You can change any OSM file into a changeset, so let's see what happens when we take an OSM file fetched from the Editing API to understand how it changes things into an OSC.

	time osmconvert sacramento-shed2015-12-16.osm -o=test.osc
	osmconvert Warning: wrong sequence at node 90639369
	osmconvert Warning: next object is node 90639367
	osmconvert Warning: wrong sequence at node 90639367
	osmconvert Warning: next object is node 90639365
	osmconvert Warning: wrong sequence at node 90725322
	osmconvert Warning: next object is node 90725316
	
	real	0m0.045s
	user	0m0.015s
	sys	0m0.014s

This is weird, of course, because we're making a changeset with something that already has been applied. Still, we can see how this tool behaves...

Here is a node that is wrapped in a `<modify>` in the `osc`:

```xml
<modify>
	<node id="3826430500" lat="38.6141114" lon="-121.4198898" version="2" timestamp="2015-11-09T11:46:48Z" changeset="35189897" uid="665694" user="aarp65"/>
</modify>
```

Looking at the source OSM file, we just see the node not wrapped in an action element:

```xml
<node id="3826430500" visible="true" version="2" changeset="35189897" timestamp="2015-11-09T11:46:48Z" user="aarp65" uid="665694" lat="38.6141114" lon="-121.4198898"/>
```

What about the `<create>` `osc` actions?

```xml
<create>
	<way id="386102792" version="1" timestamp="2015-12-16T01:26:45Z" changeset="35978898" uid="1371102" user="TheOutpost">
		<nd ref="3894443354"/>
		<nd ref="3894443355"/>
		<nd ref="3894443356"/>
		<nd ref="3894443757"/>
		<nd ref="3894443354"/>
		<tag k="building" v="shed"/>
	</way>
</create>
```

The source OSM file just has this way in there.

```xml
<way id="386102792" visible="true" version="1" changeset="35978898" timestamp="2015-12-16T01:26:45Z" user="TheOutpost" uid="1371102">
  <nd ref="3894443354"/>
  <nd ref="3894443355"/>
  <nd ref="3894443356"/>
  <nd ref="3894443757"/>
  <nd ref="3894443354"/>
  <tag k="building" v="shed"/>
</way>
 ```

The reason that this one is wrapped in a `<create>` action element is that it has a version of `1`.

This behavior is interesting, but JOSM OSM files will have elements without a version if they are new.

 	time osmconvert buildings.osm -o=buildings-via-osmconvert.osc

	real	0m0.030s
	user	0m0.008s
	sys	0m0.012s

Here is [buildings-via-osmconvert.osc](https://www.dropbox.com/s/0xr3kyo0p00ux3t/buildings-via-osmconvert.osc?dl=0).
This is __bad__. We have a new element that is being wrapped in a `<modify>` instead of a `<create>`. Let's investigate how we can do this in `osmosis` and see if that fares better...

# Merging OSC into OSM Files

Here we merge in the [larger `osc` file created by iD](https://www.dropbox.com/s/33itix0sy15j1fj/larger-osc.osc?dl=0) that we mentioned earlier.

	time osmconvert arcade-creek2015-12-16.osm larger-osc.osc -o=arcade-with-osc.osm
	'osmconvert Warning: wrong order at node -1 in file larger-osc.osc
	osmconvert Warning: next object is node -4
	osmconvert Warning: wrong order at node -4 in file larger-osc.osc
	osmconvert Warning: next object is node -7
	osmconvert Warning: wrong order at node -7 in file larger-osc.osc
	osmconvert Warning: next object is node -10
	osmconvert Warning: wrong sequence at way 10499142
	osmconvert Warning: next object is way 10499014
	osmconvert Warning: wrong sequence at way 10499190
	osmconvert Warning: next object is way 10499189
	osmconvert Warning: wrong sequence at way 139013754
	osmconvert Warning: next object is way 30429727
	
	real	0m0.051s
	user	0m0.024s
	sys	0m0.025s

You can see that `osmconvert` is complaining about a few things, but I'm not sure what. It is behaving in the way that I expect. 

Take a look at [arcade-with-osc.osm](https://www.dropbox.com/s/kpg1uz0ag75kj2r/arcade-with-osc.osm?dl=0).

This merged in an `osc` file with negative IDs. Those IDs dont get rewritten, and there is a problem with the file. It does not open in JOSM. Do we really need to merge the OSC with the OSM? It might be best to stay in OSC format...

In this instance, there is a bug with `osmconvert`. It is not including all of the nodes from the `osc`. Let's try this same thing in `osmosis` and see if it works properly.

```
time osmosis --read-xml arcade-creek2015-12-16.osm --apply-change larger-osc.osc --write-xml arcade-with-osc.osm
Dec 16, 2015 2:28:31 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.44.1
Dec 16, 2015 2:28:31 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
Dec 16, 2015 2:28:31 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Default argument for task 2-apply-change must be an integer number.
	at org.openstreetmap.osmosis.core.pipeline.common.TaskManagerFactory.getDefaultIntegerArgument(TaskManagerFactory.java:196)
	at org.openstreetmap.osmosis.set.v0_6.ChangeApplierFactory.createTaskManagerImpl(ChangeApplierFactory.java:26)
	at org.openstreetmap.osmosis.core.pipeline.common.TaskManagerFactory.createTaskManager(TaskManagerFactory.java:60)
	at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.buildTasks(Pipeline.java:50)
	at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.prepare(Pipeline.java:112)
	at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:86)
	at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: java.lang.NumberFormatException: For input string: "larger-osc.osc"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.openstreetmap.osmosis.core.pipeline.common.TaskManagerFactory.getDefaultIntegerArgument(TaskManagerFactory.java:194)
	... 15 more


real	0m0.322s
user	0m0.455s
sys	0m0.061s
```

`osmosis` is failing with this `osc`. Trying several different `osc` files, it looks like `osmosis` does not accept negative IDs.

**Comment by hallahan** [comment]
I'd rather not use changesets for our submissions from OpenMapKit Android. iD should be perfectly content with things the current way, and it's easier to work with.

**Comment by hallahan** [comment]
# Overpass Update

See: https://github.com/AmericanRedCross/posm/blob/master/STEPS.md#fetch-osm-xml

```
curl -XPOST \
  --compressed \
  -d "data=(node(-17.821343531895728, 30.904111862182614, -17.778602961844793, 30.95578193664551); <; >>; >;); out meta qt;" \
  http://overpass-api.de/api/interpreter > dvizarasekwa.osm
```

**Comment by mojodna** [comment]
I spent a little bit of time with Osmosis and generating OSCs from the APIDB. There are a few snags there--generating diffs directly from the db is exceedingly so, so it makes sense to first export to PBF and then use Osmosis to generate the diff from there.

macrocosm doesn't (currently) reset the changeset sequence, so new changesets start from 1 (and thus aren't picked up by Osmosis when exporting to PBF).

Osmosis also doesn't deal with negative IDs, so we'll likely need to rewrite the IDs present in `<create>` elements so that they're negative (and internally consistent). Oh, and this is all before attempting to submit to OSM (or queue for submission by others). We should also see if we can generate JOSM-compatible `.osm` files for manual merging.

**Comment by hallahan** [comment]
BBox for larger Arcade Creek

```
-121.384506,38.626728,-121.326056,38.667753
```

**Comment by hallahan** [comment]
It seems like the overpass query is too inclusive, and the file is unreasonably large. It includes a railroad that goes all the way into Nevada...

Here's an Arcade Creek file that's a bit smaller that uses the tried and true query from OMK Android:

https://www.dropbox.com/s/5w8382cbr853tnb/arcade.osm?dl=0

@mojodna We need to revisit our Overpass query.

**Comment by mojodna** [comment]
The streamlined version produced output that caused foreign key errors when importing into the APIDB schema (because of missing data), so I had to make it more inclusive.

**Comment by mojodna** [comment]
I think we've taken all of the actionable steps here to the extent that we have a working system. Some of this may be useful reference material for #45 and may be worth blogging at some point.
