### ISSUE TITLE
make line to edit osm dependent on url

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/posm#175]
right now the link from the home page goes to osm.posm.io which is great for local deployments not so good for cloud deployments. Make it dependent on settings.local

**Comment by mojodna** [comment]
[`osm_fqdn`](https://github.com/AmericanRedCross/posm-build/blob/f616bdd29209ade4938f18f7c3b420f008de1b5e/kickstart/etc/settings#L19) can be overridden in `settings.local` to achieve this.

**Comment by danbjoseph** [comment]
is that noted in the setup readme?
