### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#19]
POSM needs a logo.

**Comment by dalekunce** [comment]
working on it. Red Cross team will take care of this.

**Comment by dalekunce** [comment]
Red Cross team is a bit overworked at the moment. This is what we are thinking hoping Stamen or SpatialDev can have someone knock it out.

<img width="515" alt="brainstorming" src="https://cloud.githubusercontent.com/assets/1913857/12061013/4de35620-af49-11e5-9428-71805284ee82.png">

cc @AmericanRedCross/stamen @AmericanRedCross/spatialdev

**Comment by mojodna** [comment]
Alec, one of our designers, took inspiration from the above but also took a little creative freedom. He felt that simplifying it would make for a more recognizable mark and increase its legibility at smaller sizes.

![image](https://cloud.githubusercontent.com/assets/45/12104260/9aa9109a-b2fe-11e5-9b61-dbd9a054c8af.png)

![image](https://cloud.githubusercontent.com/assets/45/12104264/9d48a202-b2fe-11e5-8d6f-23c84dee0f0f.png)

![image](https://cloud.githubusercontent.com/assets/45/12104267/a05d57a8-b2fe-11e5-8e5b-67a173c97bcc.png)

Greyscale has a certain appeal given the medium. Is there a particular color scheme that makes sense for these tools, or should I let Alec know that he has free rein there too?

**Comment by hallahan** [comment]
I really really like this. If we introduce color, perhaps OSM colors would help with brand recognition?

**Comment by mojodna** [comment]
![image](https://cloud.githubusercontent.com/assets/45/12105383/194d362e-b309-11e5-9c1a-26c85cae1f14.png)

![image](https://cloud.githubusercontent.com/assets/45/12105387/1bf49b92-b309-11e5-80c4-5d7b84aa1027.png)

![image](https://cloud.githubusercontent.com/assets/45/12105388/1f3015de-b309-11e5-9858-d2669421a013.png)

**Comment by dalekunce** [comment]
ohh I like the red one of course :)

Can we get a fatter S.

**Comment by dalekunce** [comment]
changed my mind I like the black and white one.

**Comment by alecburch** [comment]
New typeface. This one isn't as chunky and has a more consistent character width which I believe is what @dalekunce didn't care for with the previous choice. I'm really happy with this one. 

![screen shot 2016-01-05 at 1 06 09 pm](https://cloud.githubusercontent.com/assets/5263476/12127667/52c61340-b3ad-11e5-9676-2df422b68b94.png)
![screen shot 2016-01-05 at 1 06 15 pm](https://cloud.githubusercontent.com/assets/5263476/12127669/52c9a546-b3ad-11e5-8841-dcb8588c4448.png)
![screen shot 2016-01-05 at 1 06 24 pm](https://cloud.githubusercontent.com/assets/5263476/12127668/52c717d6-b3ad-11e5-8232-53375564e623.png)

**Comment by dalekunce** [comment]
Perfect. I love it.

**Comment by dalekunce** [comment]
Can you send over the ai file.

**Comment by mojodna** [comment]
[POSM_logo-build.ai](https://files.zenhub.io/568c526d25e446e21bcd998a)

**Comment by emilyeros** [comment]
@alecburch This is great! Could you share the font with us? The ai file just has compound paths, and it might be useful for some infographics we're putting together to explain POSM.

**Comment by mojodna** [comment]
@emilyeros check #posm on the OMK slack.

**Comment by alecburch** [comment]
@emilyeros, sorry, I was out yesterday. were you able to get the font file?

**Comment by emilyeros** [comment]
@alecburch I did - thanks!
