### ISSUE TITLE
Push OpenDroneMap Docker image to a registry

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#198]
Quay.io and Docker Hub both support automatic building of images when commits are pushed to GitHub, so we need to decide which one.

`Dockerfiles` for ODM are up-to-date on the `dev` branch.

**Comment by jjmata** [comment]
Happy to help here.  I had some success setting one up in Docker Hub, but had to get creative given the 2/3 hour time limit imposed on builds there.

Finally got dev (and associated `packages` pre-build image) working there a few days ago.  But haven't updated it since/looked at it.

**Comment by jjmata** [comment]
Oops.  Thought this was the ODM repo I was responding in ... ;-)  Not sure what the etiquette is here at POSM.

Regardless, happy to help as well.  🙌

**Comment by mojodna** [comment]
Oh, awesome! In that case, I'll give Quay a shot and see if I have better luck w/r/t timeouts. I suspect we may want/need to track a different branch for POSM at some point (and we need to Dockerize a bunch of other components).

Where are your images? I'll probably use those to get up-to-speed until there's a reason not to.

**Comment by jjmata** [comment]
Take a look [here](https://hub.docker.com/r/splashblot/opendronemap/).

I also have a PostGIS image there that might be of interest.  It's gotten 1k pulls out of nowhere in a few days since creating it and never telling anybody about it.  O_O

**Comment by mojodna** [comment]
Minimal (280MB) image pushed to Docker Hub: https://hub.docker.com/r/mojodna/opendronemap-minimal/

(Small is good so it doesn't bloat the installer.)

`Dockerfile`: https://github.com/mojodna/docker-opendronemap-minimal
