### ISSUE TITLE
Gather test sets for ODM processing

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#211]
We have imagery from Seattle University, although that requires getting lens distortion info from the checkerboard photos.

**Comment by danbjoseph** [comment]
The ODM repo has some datasets? See the 'Example Data' nav option at http://opendronemap.github.io/odm/

**Comment by mojodna** [comment]
![image](https://cloud.githubusercontent.com/assets/45/18072254/8358ae40-6e11-11e6-9397-a70f87764038.png)

(https://github.com/OpenDroneMap/odm_data)

makes me want to gather more! (especially if we can gather some captured with the same gear you're taking with you)

**Comment by mojodna** [comment]
Imagery from Seattle University (Phantom 3 Standard + DroneDeploy) is here: https://github.com/mojodna/odm_seattle_university

**Comment by mojodna** [comment]
Calibration images for the Phantom 3 Standard are here: https://github.com/mojodna/dji_fc300c

**Comment by mojodna** [comment]
I've been using a pair of additional imagery sets covering a farm outside Seattle as well as imagery collected by the World Bank in Argentina (which has proved to be a nice stress test for ODM).

**Comment by jjmata** [comment]
What sort of "stress" are you looking for testing here, @mojodna?  Seams?  Exposure compensation?

**Comment by mojodna** [comment]
Size / memory pressure to determine whether we've sized the recommended POSM hardware for ODM appropriately. Getting deep into ODM is (was) out of scope for this project, excepting improving packaging and picking off some low-hanging resource utilization optimizations (parallelization of cpu-limited Python processing).
