### ISSUE TITLE
POSM / OpenDroneMap Workflow

### ISSUE THREAD

**Issue by emilyhobson** [AmericanRedCross/posm#218]
(@mojodna here)
## UAV photos → GeoTIFF
1. Upload / copy photos to POSM (web UI for bulk uploading of images w/ progress meter)
2. (later) Group photos into "projects"
3. Select photos to process
4. Process with OpenDroneMap (black box)
   5a. View progress
   5b. Cancel processing
   5c. Restart processing
5. Show resulting artifacts: GeoTIFF (thumbnail, browsable map), 3D model (later), point cloud (later)
## GeoTIFF → tiles
1. (optional) Upload / copy GeoTIFFs to POSM (web UI for bulk uploads w/ progress meter)
2. (later) Group / move scenes into "projects"
3. Select GeoTIFFs to process
4. (later, optional) Select area of interest
5. Process with ___ (black box)
   6a. View progress
   6b. Cancel processing
   6c. Restart processing
6. Show resulting artifacts: browsable map, downloadable MBTiles archive, GDAL WMS source, POSM URL template/TileJSON for use with Field Papers, JOSM, iD, etc.

**Comment by emilyhobson** [comment]
- Upload a photo
- Name photos (?)
- (?Crop photo)
- Group photos into projects
- Choose photos to process 
- User can view progress of processing (cancel and restart)
- GeoTiff results - thumbnails of GT; download the GT
- Select GT to make into tiles 
- Download MBtile to downloading 
-

**Comment by mojodna** [comment]
Investigate http://tus.io/ (especially for GeoTIFFs) when implementing uploading.

**Comment by mojodna** [comment]
See https://vimeo.com/190617847 for a demo.
