### ISSUE TITLE
Coordinate GPS from camera and/or photo

### ISSUE THREAD

**Issue by emilyhobson** [AmericanRedCross/posm#220]

**Comment by danbjoseph** [comment]
fyi, this is how we are planning to collect coordinates for the images taken by the tuffwing 
http://www.tuffwing.com/support/Install_a_canon_precision_geotag_cable.html

**Comment by danbjoseph** [comment]
pg 17-18 of the E384 manual [(pdf here)](http://droneyard.com/e384opsman.pdf) describes how those pictures are geotagged

**Comment by mojodna** [comment]
@emilyeros to dig up the tool that's used to add EXIF data to photos when collecting for Mapillary.

**Comment by hallahan** [comment]
FYI: https://github.com/hallahan/exif-to-geojson

**Comment by mojodna** [comment]
Reading these makes me think that we should support uploading and (enhanced) viewing of a Pixhawk log file (i.e. to see where pictures were taken and to link to the pictures themselves, if that can be determined).

@danbjoseph let's take a look at the resulting log file after you go to NJ to fly.

**Comment by mojodna** [comment]
@hallahan sweet, that'll be useful too, I think.

**Comment by danbjoseph** [comment]
not sure what tool emily was referencing. if it was something originally from mapillary, then the most recent version (and what i've used lately for uploading pics from a Garmin Virb) would be at https://github.com/mapillary/mapillary_tools/tree/master/python

**Comment by mojodna** [comment]
Adding to the list of potentially helpful stuff: https://github.com/aaronr/geosync

**Comment by mojodna** [comment]
Waiting on @danbjoseph et al being able to try out the Tuffwings.

**Comment by mojodna** [comment]
Err, actually, this was about feeding coordinates to ODM, which now works.
