### ISSUE TITLE
Ground Control Point interface (GCPi)

### ISSUE THREAD

**Issue by emilyhobson** [AmericanRedCross/posm#221]
(@mojodna here)

Goal: establish coordinate pairs between images (pixels within individual images) and the world (lon/lat).

Input: set of photos (on the order of 100?)
Output: list of coordinate pairs (lon, lat, elevation, pixel x, pixel y, filename)

Sample output (from https://github.com/merkato/odm_boruszyn_kap/blob/ebb9da3d6108322c7c9fb24747b7fa86b1adc8bb/gcp_list_wgs84.txt):

```
EPSG:4326
16.63593223 52.77337048 70 691 3498 img_4851.jpg
16.63632082 52.7752311 71 1248 2921 img_4854.jpg
16.63687673 52.77564693 70 1078 2312 img_4912.jpg
16.63637911 52.77525025 70 1358 1934 img_4939.jpg
16.63544998 52.77433227 70 501 2949 img_4946.jpg
16.63241843 52.77307551 72 3792 1767 img_4873.jpg
16.63801669 52.7745903 70 2139 266 img_4883.jpg
```

Potential interface idea: image thumbnails (to select active image), active image (clickable to connect pixels with a point on the map), map (clickable to connect points with pixels)

@sconnelley and I discussed rotation of images for display as a map overlay, but given the number of GCPs needed to seed ODM, we won't even have 1:1 (GCP : image), so we have no way to determine rotation. Plus, ODM will handle all of that for us.

/cc @smathermather for an estimate as the typical number of images that are used as input to ODM as well as recommendations about how to deal with elevation.

**Comment by mojodna** [comment]
First step: @sconnelley is going to build a prototype interface with an initial pass on the interface using one of the [odm_data](https://github.com/OpenDroneMap/odm_data) datasets.

**Comment by smathermather** [comment]
One thing we'll need to keep in mind that may drive interface design is that the requirements for the GCP file will be as follows with upcoming work on OpenSfM that moves GCPs into that part of the tool chain. At that time, ODM will requires 2 observations per GCP, with an absolute minimum of 3 GCPs (I would recommend we make that minimum 4 for any interface development).

@dakotabenjamin: what are the current requirements for GCPs (having trouble finding it in the wiki)?

**Comment by mojodna** [comment]
By "2 observations per GCP" you mean that each GCP needs to be marked in at least 2 separate source images?

**Comment by smathermather** [comment]
Correct.

**Comment by dakotabenjamin** [comment]
Found here: https://github.com/OpenDroneMap/OpenDroneMap/wiki/Running-OpenDroneMap#running-odm-with-ground-control

**Comment by smathermather** [comment]
Ah, it's more stringent:

> high-contrast objects that are found in at least 3 photos, and that you find a minimum of 5 objects.

**Comment by mojodna** [comment]
https://github.com/wolkstein/OpenDroneMap-GCP_LIST.TXT-generator is a potentially useful approach to incorporate in future when GCP markers are used.

**Comment by smathermather** [comment]
That's pretty cool.
