### ISSUE TITLE
Admin interface framework

### ISSUE THREAD

**Issue by emilyhobson** [AmericanRedCross/posm#222]
(@mojodna here)

The need for a common interface framework is becoming apparent, initially across POSM Admin, the OpenDroneMap workflow manager (for POSM), and the ODM ground control point establishment tool.

POSM Admin uses [Material Design Lite](https://getmdl.io/), which includes basic UI components à la Bootstrap.

It's becoming clearer that having a set of higher-level components that form an administrative interface would be very helpful. The benefit is that new POSM components could include just the UI components that slot into an existing interface.

(We'd also want to consider something that could be used for additional Red Cross (and other humanitarian stack) tools in the future so that knowledge and code can be re-used.)

To that end, we've identified a couple of promising candidates (that @alecburch and @sconnelley are evaluating from design and implementation perspectives):

* https://almsaeedstudio.com/preview (Bootstrap-based)
* https://colorlib.com/polygon/gentelella/ (Bootstrap-based)

These provide pre-defined combinations of components for specific purposes and are intended to be responsive from day 1 (so they'll work well on mobile).

While doing some additional research this morning, [Limitless](http://demo.interface.club/?theme=limitless) looks like a credible Material Design-influenced version, should we want to stay on that route.

**Comment by dalekunce** [comment]
what is the thought behind leaving the basic framework behind. I'm usually not a fan of embrace the new library or framework. I do like things to be stock as much as possible exactly for the reason you set out, repeatable and easy to use.

**Comment by mojodna** [comment]
MDL doesn't include the higher-level components (which create widgets out of the lower-level UI pieces) that we'd like to be able to treat as units (e.g. responsive nav + dashboard). We _could_ create them, but then we'd be recreating one of the admin templates above.

My sense is that (for this), it's better to start with a kitchen sink (admin) framework that includes full-blown [responsive] wizard UIs and cut it back rather than needing to create each from scratch (using MDL-style buttons, divs, etc.) each time we need it.

**Comment by dalekunce** [comment]
Makes total sense. 

I like https://colorlib.com/polygon/gentelella/ of the options you showed.

**Comment by hallahan** [comment]
Looks really nice on mobile!

**Comment by mojodna** [comment]
https://github.com/mojodna/posm-admin-ii uses Gentelella (and Bootstrap) CSS within a [Gatsby](https://github.com/gatsbyjs/gatsby) static site. Content can be added as HTML, Markdown, React components, etc.
