### ISSUE TITLE
Deploy macrocosm

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#24]
Deploy from `master` here: https://github.com/americanredcross/macrocosm

(If there are changes you'd like to see that would make deployment easier, let me know.)

N.b.: this needs to be mounted at `/` because iD is hard-coded to look for API endpoints there (and is difficult to configure otherwise). Perhaps this should be the fallback.

**Comment by jflemer-ndp** [comment]
your changes are on `develop` ...

**Comment by mojodna** [comment]
Err, yeah. Forgot about that. That's what I meant ;-)

**Comment by jflemer-ndp** [comment]
Working on it ... (note macrocosm needs nodejs v5)

**Comment by jflemer-ndp** [comment]
Well, initial deployment "works" in that the service is now running on port 4000.  Beyond that, I haven't had time to test.  Others can test (after pulling latest build scripts) with:
```
/root/scripts/bootstrap.sh macrocosm
```

**Comment by jflemer-ndp** [comment]
Do you have a preference for the url where macrocosm gets deployed? How about /osm/0.6 or should it be /api/0.6 to match http://api.openstreetmap.org/api/0.6?

**Comment by dalekunce** [comment]
can we do /osm/api/0.6

**Comment by jflemer-ndp** [comment]
@mojodna since you've looked at iD, what do you think? Does it support a different base url or just a different hostname?

**Comment by mojodna** [comment]
Just a different hostname. Most endpoints are under `/api/0.6`, but there's at least one without `0.6`. 

Hadn't thought through that earlier--seems like proxying `/api` should be sufficient. Just means our own API will need to be mounted elsewhere.

**Comment by jflemer-ndp** [comment]
Ok, I'm going to use `/api` for now.  If we later determine iD can support a different base url (or patch it to do so), we can update the proxy config.

**Comment by mojodna** [comment]
Confirmation dependent on #27 (though non-db-related queries appear to work).

**Comment by jflemer-ndp** [comment]
DB queries work as well (now), and iD shows editable layer

**Comment by mojodna** [comment]
Yay!
