### ISSUE TITLE
Make iD available

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#25]
(Static hosting)

Use the version of iD here (contains changes to avoid auth + use `posm.local` instead of `www.openstreetmap.org`): https://github.com/americanredcross/id

**Comment by jflemer-ndp** [comment]
working...

**Comment by jflemer-ndp** [comment]
Do you have a preference for the url where macrocosm gets deployed? How about `/osm/0.6` or should it be `/api/0.6` to match http://api.openstreetmap.org/api/0.6?

**Comment by jflemer-ndp** [comment]
oh, iD now literally uses `posm.local`... how much effort to make it configurable?

**Comment by jflemer-ndp** [comment]
Meh, I used `sed` to make it "deploy-time" configurable.

**Comment by mojodna** [comment]
Yeah, that was basically going to be my approach too.
