### ISSUE TITLE
OMK Provisioning Workflow

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#26]
(Yanked from https://github.com/AmericanRedCross/OpenMapKitWebsite/issues/9)

@hallahan what does this need to do (and which components does it touch)? It seems like there are initially 2 pieces: 1) getting forms (?) onto the portable server from the web when preparing to go into the field, 2) getting forms onto individual Android devices (from the portable server).

Can you elaborate, even if you're the one who's going to implement this, so we have a clearer idea of what the process looks like (and can fake it by hand in the meantime)?

/cc @dalekunce

**Comment by mojodna** [comment]
Flagging for in-person discussion on Thursday.

**Comment by mojodna** [comment]
See also https://github.com/AmericanRedCross/OpenMapKitServer/issues/7

**Comment by hallahan** [comment]
Getting forms onto the portable server as well as phone is done.

**Comment by mojodna** [comment]
@hallahan looks like the remaining piece is documenting this, in `STEPS.md` and elsewhere.

**Comment by hallahan** [comment]
We're going to achieve this via #121. Uploading forms can and should be done on the POSM. No need for that to be part of cloud HOT Export tool.
