### ISSUE TITLE
Local Instance of openmapkit.org

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#260]
Similar to [posm-admin2](https://github.com/AmericanRedCross/posm-admin2), get a local instance of openmapkit.org working from the home screen on POSM.

* [x] Within the `posm-local-home` project, add a [submodule](https://github.com/AmericanRedCross/posm-local-home/blob/master/.gitmodules) to a branch of OpenMapKitWebsite where the Jekyll project has already been built. Name that branch on OpenMapKitWebsite to `dist`.
* [x] Fix the paths in the Jekyll project so that all links and assets work when the site is hosted from a subpath from root.
* [x] Make sure that all of the images and other assets are hosted locally on the project.

**Comment by mojodna** [comment]
> Name that branch on OpenMapKitWebsite to dist.

You can probably re-use the `gh-pages` branch, as relative paths should continue to work when it's used for openmapkit.org.

**Comment by hallahan** [comment]
The `gh-pages` branch does not include the compiled product, just the jekyll source. I think it would be better to have the compilation be deployed on POSM.

**Comment by mojodna** [comment]
Right, of course.

**Comment by hallahan** [comment]
I need to look into seeing how to get the Google fonts to be offline as well. Though, the fonts not coming through might be fine...

**Comment by hallahan** [comment]
I'm going to remove Google Fonts. Turns out Helvetica is prioritized in the CSS anyway, so you usually won't see the Google font anyway...

**Comment by hallahan** [comment]
@mojodna - I have completed this issue and will have a PR for you in `posm-local-home`. Note that the Github Jekyll build breaks. Waiting on @danielduhh on how to proceed with that, but the actual compiled `dist` branch is working fine.
