### ISSUE TITLE
Investigate OMK Server OSM API -> iD

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#29]
We need exports from OMK Server to get to iD. It may be direct, or it may be via macrocosm. We must investigate iD to determine how we want to do this.

**Comment by mojodna** [comment]
@hallahan this is working, correct?

**Comment by hallahan** [comment]
Yes, it is done. Note we have encountered a bug.

https://github.com/AmericanRedCross/OpenMapKitServer/issues/28
