### ISSUE TITLE
Validate XLS → XForm conversion when provisioning a new area

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#30]
...beats discovering later that it was invalid.

**Comment by mojodna** [comment]
@hallahan how important is this?

**Comment by hallahan** [comment]
This is already in place in OpenMapKit Server. There is a form upload page, and an end point that converts and validates.

Rather than re-invent the wheel, we should just have node post to the form upload endpoint. Then we know it's in the right place.

**Comment by hallahan** [comment]
https://github.com/AmericanRedCross/OpenMapKitServer/blob/master/api/odk/odk-aggregate-routes.js#L19

**Comment by hallahan** [comment]
I'm not so sure this is very important. It's easy enough to just upload an XLS form in OpenMapKit Server. I guess this could make sense to automatically do that when POSM sees the XLS file in the cloud archive.
