### ISSUE TITLE
Deal with captive portal detection on various devices

### ISSUE THREAD

**Issue by jflemer-ndp** [AmericanRedCross/posm#32]
See https://github.com/AmericanRedCross/posm/issues/10#issuecomment-175206508

Need to:
 - decide what devices we actually care about
 - determine on those devices if we need to:
   - "spoof" the captive portal detection to make it think it's not captive
   - comply with the captive portal detection so it thinks it has "logged in"
   - or just make it think it's on a non-captive, non-internet network
 - then implement the right tricks in dnsmasq and Nginx etc to resolve

**Comment by jflemer-ndp** [comment]
For instance, my android (5.1.1) phone doesn't do anything as "helpful" as @mojodna's iPhone. It just connects, and my browser gets redirected as expected if I try some arbitrary http url.

**Comment by mojodna** [comment]
Android 4 appears to do something similar to CNA: http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/4.0.1_r1/android/net/wifi/WifiWatchdogStateMachine.java#WifiWatchdogStateMachine.isWalledGardenConnection%28%29

We should test with an ARC-standard Android phone (Galaxy S3/S4 + Android v???)

**Comment by dalekunce** [comment]
Samsung S3/S4/S5 is what we mostly have deployed in the field. All devices are Android 4.4 or better.

**Comment by hallahan** [comment]
Nothing shows up in captive portal on my Macbook Pro.

<img width="900" alt="screenshot 2016-02-22 14 17 37" src="https://cloud.githubusercontent.com/assets/556367/13234867/baf1ea88-d96f-11e5-8480-858f3781db20.png">

However, I do the POSM screen when explicity going to http://posm.local in Chrome.

**Comment by mojodna** [comment]
Tested on both BLU and Samsung phones.

**Comment by ziedbh** [comment]
Hello, I have an issue detected only on samsung s4 and j7 but ok on others (ios, lenovo, asus, huawei)
I installed a webserver with captive portal on a raspberry with a hotspot (nginx/apache2/lighttpd, hostapd, dnsmasq) when i connect to this wifi network a popup "Sign-in to network" is displayed or an auto launch of the captive portal page is done.
This behavior failed only on some samsung smartphone like s4 and j7, when i connect nothing happened!!! no popup nor auto display CP page
any proposition?

**Comment by mojodna** [comment]
Have a look at the web server logs to see what the different phones are probing. Different manufacturers probe different endpoints for network connectivity and need to be provided certain responses to convince them that the network is available. POSM configures the following:

https://github.com/posm/posm-build/blob/1d90981045e0d529a5cb65d72f72621300e47ee2/kickstart/etc/nginx-captive.conf#L5-L25
