### ISSUE TITLE
Domains

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#37]
We'll initially want 2 domain names for use with POSM, 1 for the public presence, 1 for devices to advertise (for which we'll get an SSL certificate).

**Comment by dalekunce** [comment]
Just to be clear the public presence is a real domain and 1 for devices is a throwaway.

**Comment by dalekunce** [comment]
submitted a ticket with our internal IT for:

posm.io
localposm.com

**Comment by mojodna** [comment]
Once you can verify ownership + set up DNS for a localposm.com subdomain, we can get a real cert for devices that we can replace w/ a new subdomain as necessary.

**Comment by dalekunce** [comment]
domains completed, working on the cert

**Comment by mojodna** [comment]
@dalekunce what's the status on the cert?

**Comment by dalekunce** [comment]
talked my IT folks today. they need to get some higher level approvals or something because they are non RC domains.

**Comment by emilyhobson** [comment]
Any change on the approvals, @dalekunce?

**Comment by dalekunce** [comment]
got the certs today. :+1:
