### ISSUE TITLE
Install atlas printer / snapshot processor tools

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#4]
Consult https://github.com/fieldpapers/fp-legacy/blob/modernize/decoder/Dockerfile for dependency info + target locations (assumes `decoder/*` is installed into `/opt/paper`).

(And yes, it does shell out to PHP to do the final PDF conversion, since that PDF lib can do JPEG compression of embedded images.)

Python deps are split between OS packages (in `Dockerfile`) and `requirements.txt` (which should probably contain everything).

I haven't spent a whole lot of time cleaning this up because I've been hoping to replace it with simplified alternatives (OpenCV-based snapshot processor, `wkhtmltopdf`-based printer).

**Comment by jflemer-ndp** [comment]
working

**Comment by jflemer-ndp** [comment]
meh, `vlfeat` doesn't compile so nice on Ubuntu 14.04 at the specified version

**Comment by jflemer-ndp** [comment]
Looks like FP Legacy is missing `celery`, `redis` and `BeautifulSoup` from `requirements.txt`.  Added them to the deploy script, but not at any specific version.  And now can run `celery` with the defined tasks (doesn't connect, since `redis` is not running though).

@mojodna Is celery running the desired goal?

**Comment by mojodna** [comment]
No, actually (sorry). Celery is part of the "legacy" bit.

The goal should be for the command-line runners (`create_index.py`, `create_page.py`, `snapshot.py`, `read_qr_code`) to execute, nothing more.

Also, you're on the `modernize` branch, correct?

**Comment by jflemer-ndp** [comment]
Got it, that makes more sense. (Yes on the branch)

**Comment by mojodna** [comment]
:+1:

The command-line runners are assumed to be in place by `fp-tasks` and executed by that.
