### ISSUE TITLE
Deploy posm-carto

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#42]
https://github.com/AmericanRedCross/posm-carto

`make xml` (assuming appropriate dependencies have been installed) will produce an XML file that can be pointed to in `/etc/tessera.json`

For @jflemer-ndp or @mojodna, whoever gets to it first.

**Comment by jflemer-ndp** [comment]
Do we want to put all the dependencies on the box?

**Comment by jflemer-ndp** [comment]
Working this ...

**Comment by mojodna** [comment]
> Do we want to put all the dependencies on the box?

For now, yes.

FWIW, it may be helpful to know my philosophy on deploying map styles: they're no different from apps and include necessary server components to render themselves (i.e. `npm install && npm start` will open a tileserver on `$PORT` without requiring any npm dependencies outside the project tree).

In our case, we just want the generated XML so it can be served by the globally-installed `tessera` (along with other styles, MBTiles, etc.)

**Comment by jflemer-ndp** [comment]
No prob.

**Comment by jflemer-ndp** [comment]
![mm-carto](https://cloud.githubusercontent.com/assets/1520812/12740130/7d5bd6f4-c92d-11e5-9d9b-bbf76938810e.png)

Works, though for now having to pull one font independently.
