### ISSUE TITLE
Tune puma concurrency (for FP) or investigate Passenger

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#44]
Realistically, how many people are going to be accessing FP simultaneously? Enough to warrant doing this?

I mention Passenger ([comparison here](https://github.com/phusion/passenger/wiki/Puma-vs-Phusion-Passenger)) in case we want to run the OSM Rails Port for API purposes and it turns out easier / more efficient to use Passenger (not sure if it does, just throwing this out there).

**Comment by jflemer-ndp** [comment]
On a small device (NUC), concurrency might not be the best plan. But we can definitely look into this.

**Comment by mojodna** [comment]
We'll keep an eye on performance once this is being used by multiple people, but I'm happy with the current config.
