### ISSUE TITLE
Changeset replay tool

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#45]
To support local rebases (against new extracts or deltas) as well as to prepare for submission of changes to OSM.org.

Per voice discussion between @jflemer-ndp and @mojodna

**Comment by hallahan** [comment]
We need to move the changeset-replay-tool repo to AmericanRedCross.

**Comment by emilyhobson** [comment]
Can you break this down into smaller deliverable parts, @mojodna?

**Comment by mojodna** [comment]
Current state is at https://github.com/AmericanRedCross/posm-replay-tool and was successfully used for importing the edits made by volunteers in Ecuador.

Documentation and clean-up is still necessary, but those can (and should) be tracked as smaller, discrete issues.
