### ISSUE TITLE
Run bootstrap scripts with `-e`

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#47]
Ran into a problem this morning where `wget -q -O - https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -` failed (presumably bad data upstream) and the bootstrap process kept going, although without `nodejs`, so it formed a broken system.

**Comment by mojodna** [comment]
(Ignoring going full idempotent for now, as some other provisioning mechanism is more suited to that.)

**Comment by jflemer-ndp** [comment]
Agree, there is little to no error handling in this now.  I want to combine this with #46 though with the same comment: move to chef, ansible, and/or deb packages.  `bootstrap` was intended to be an interim solution until HW platform was finalized (i.e. know if we were going to use an embedded os, rasperry pi, regular x86 / NUC, or other).  If we are ready to say regular x86 (x64) Ubuntu is the platform, then we can move to real deployment tooling.

**Comment by jflemer-ndp** [comment]
As for short term, `-e` might be workable, but its a massive hammer and will cause a bit of defensive code.  I'd prefer to just have a set of "post-deploy" checks that run instead (as those would be useful with any deploy tool, and for CI etc).

**Comment by mojodna** [comment]
Works for me, especially since re-running it _does_ work.
