### ISSUE TITLE
MBTiles tools

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#5]
We'll want [`tl`](https://github.com/mojodna/tl) available, along with [mbtiles](https://github.com/mapbox/node-mbtiles) and [tilelive-http](https://github.com/mojodna/tilelive-http) to wrangle and update MBTiles archives.

`sqlite3` is statically compiled into `mbtiles`'s dependency, though having the command-line utility will also be useful (for merging archives: https://github.com/mapbox/mbutil/blob/master/patch).

**Comment by jflemer-ndp** [comment]
Installed `tl` globally with bundled mbtiles and tilelive-http.  Sqlite was already installed by something else, but put it along with these tools just incase the other thing pulling it in goes away.
