### ISSUE TITLE
Change default background tiles in iD

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#51]
Current Mapbox Satellite, but needs to be something that will work offline.

**Comment by dalekunce** [comment]
Ideally we can handle this with the current out of scope need for some imagery processing workflow.

**Comment by mojodna** [comment]
Done in https://github.com/AmericanRedCross/iD/commit/0b100a700f2b9cd12be42638ff225c9b3d440a09 by turning the background off.

**Comment by mojodna** [comment]
Custom background tiles can be passed in as URL arguments, which gives us the ability to use any tiles that are available on the device (including tiled snapshots).
