### ISSUE TITLE
Verify that fp-web works

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#6]
(And probably write a brief regression check that hits a page that's known to use the database.)

Since https://github.com/fieldpapers/fp-web/pull/13, `DATABASE_URL` has been expanded into `RDS_*` (to better match environment variables that are automatically set via AWS Elastic Beanstalk). Please open issues against [fieldpapers/fieldpapers](https://github.com/fieldpapers/fieldpapers) as you run into especially annoying configuration issues.

**Comment by jflemer-ndp** [comment]
Have fp-web itself working it looks like (loads self and assets on port 80 at a `/fp` url path).  Working on getting it to work correctly with the other parts (`fp-tasks` and `fp-legacy/decoder`).

**Comment by mojodna** [comment]
Verified!
