### ISSUE TITLE
Configure + deploy CGImap

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#63]
Wire up w/ nginx + fastcgi.

This replaces parts of the Rails app's API endpoints with more performant versions.

**Comment by hallahan** [comment]
I'd like to help with this.

**Comment by hallahan** [comment]
Looks like there are 2 repos:

Main:
https://github.com/zerebubuth/openstreetmap-cgimap

OpenStreetMap Mirror:
https://github.com/openstreetmap/cgimap
