### ISSUE TITLE
Initial mapnik install fails (for each new project)

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#67]
Presumably because `node-pre-gyp` isn't installed first. Seems like an npm problem. I _think_ the build scripts currently work around this, resulting in a working system.

```
npm ERR! Linux 3.19.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "mapnik"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! mapnik@3.4.16 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the mapnik@3.4.16 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/tl/npm-debug.log
```

**Comment by jflemer-ndp** [comment]
You found this in the log or due to a symptom?

**Comment by mojodna** [comment]
Log.

Things end up being fine (I think--there may be multiple `mapnik` deps installed where there should only be 1), but I'd like to track down the root cause at some point.

**Comment by mojodna** [comment]
These seem to be occurring when `mapnik` was already installed somewhere in the dependency tree. I removed the installation of `mapnik` into `tessera`, as it's now bundled (for thumbnails).

`tl` indirectly depends on `mapnik` (via `abaculus`) for tile stitching. In that case (since we're doing a non-standard thing and installing additional, unspecified dependencies into its `node_modules/`), we should probably delete `abaculus`' and re-install it in the root. I'm curious whether the above errors will go away if `mapnik` is removed first.

**Comment by jflemer-ndp** [comment]
Does node have anything like Debian `--(no-)install-recommends` so that mapnik could be a recommended package and installed as a (optional) top level dep?

**Comment by mojodna** [comment]
npm has 4 types of dependencies:

* `dependencies` - what you'd expect
* `devDependencies` - dependencies needed for developing (test runners, etc), installed when running `npm install` in a module's working directory or via `npm install --dev`
* `optionalDependencies` - will be installed alongside `dependencies`, but installation failures aren't treated as critical. This seems like the most similar to Debian's recommended dependencies (although in this case, Mapnik is a required dep)
* `peerDependencies` - required parallel dependencies (at the same level of the tree as the module declaring it). these used to be installed automatically, but not since npm 3. This seems like what you're describing behavior-wise. We explored this at one point, but weren't sure that it was behaving properly and would have had to update the dependencies of most things that depend on Mapnik to actually address it.

Our interim workaround for removing duplicate Mapnik dependencies has been:

```bash
find node_modules -type d -name mapnik -exec rm -rf {} \;
npm install mapnik
```
