### ISSUE TITLE
Script rendering database population

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#7]
...using an arbitrary extract file (likely the only argument to the script). Use something small to test.

Let's start with `osm2pgsql` using [`hstore.style`](https://gist.github.com/mojodna/10551920). The end result should be a set of tables w/ all tags stored in `tags` columns (and with no tags expanded into columns; if we need that to match other styles, we can create views). (`-j|--hstore-all` is the option that creates this table).

Intermediate tables (nodes, ways, relations) required for `--append` are unnecessary, as our AOIs should be sufficiently small that reimporting will be good enough.

**Comment by jflemer-ndp** [comment]
First pass is committed, doesn't include style. Use `bootstrap.sh demo_data`.

**Comment by jflemer-ndp** [comment]
That style doesn't work for me:
```
gis@mmfs2:~$ osm2pgsql --hstore-all --style=/opt/gis/hstore.style --slim -C 1801 --number-processes 2 '/tmp/demo_data.pbf'
osm2pgsql SVN version 0.88.1 (64bit id space)

Unknown flag '' line 1, ignored
Unknown flag '' line 2, ignored
Using built-in tag processing pipeline
Osm2pgsql failed due to ERROR: No columns provided for table planet_osm_point
```
See https://github.com/openstreetmap/osm2pgsql/issues/272?

**Comment by jflemer-ndp** [comment]
Not sure what you wanted on line 1 & 2, but adding the following to avoid the no `planet_osm_point` issue:
`node    asdfasdf        text    linear`

**Comment by jflemer-ndp** [comment]
Looks like `way_area` and `z_order` (line 1 and 2) worked as expected, despite the `Unknown flag` message.

**Comment by mojodna** [comment]
Weird! What version of osm2pgsql? Ill try to figure out what changed
later...that style used to work.

**Comment by mojodna** [comment]
Err, I see the version now.

I'm having good luck with the style bloe (which replaces the junk column w/ `z_order`, which is sometimes relevant for points).

I'm using a slightly more convoluted command line:

```bash
osm2pgsql --unlogged --number-processes 4 -v -c -d simple -H localhost -k -S hstore.style --hstore-add-index --extra-attributes delaware-20151208.osm.pbf
```

(`-k`, `-j`, doesn't seem to matter. `--extra-attributes` adds some more tags (`osm_uid`, `osm_user`, `osm_version`, `osm_changeset`) that could be convenient and/or interesting.)

```
node            z_order         int4
way             way_area        real
way             z_order         int4

# These tags can be long but are useless for rendering.
# This indicates that we shouldn't store them.
# List from <http://lists.osm.org/pipermail/dev/2012-June/025046.html>
# OsmType  Tag          DataType     Flags
node,way        3dshapes:*      text    delete
node,way        AND_nosr_r      text    delete
node,way        b5m:*   text    delete
node,way        bak:*   text    delete
node,way        canvec:*        text    delete
node,way        created_by      text    delete
node,way        dcgis:* text    delete
node,way        FIXME   text    delete
node,way        geobase:*       text    delete
node,way        gnis:*  text    delete
node,way        kms:*   text    delete
node,way        KSJ2:*  text    delete
node,way        massgis:*       text    delete
node,way        mvdgis:*        text    delete
node,way        naptan:*        text    delete
node,way        ngbe:*  text    delete
node,way        nhd:*   text    delete
node,way        NHD:*   text    delete
node,way        note    text    delete
node,way        note:*  text    delete
node,way        notes   text    delete
node,way        osak:*  text    delete
node,way        source  text    delete
node,way        source:*        text    delete
node,way        sourcedb:*      text    delete
node,way        tiger:* text    delete
node,way        WroclawGIS:*    text    delete
node,way        yh:*    text    delete
node,way        rednap:* text   delete
node,way        ideewfs:* text  delete
node,way        ign:* text      delete

# mark ways as polygon without creating a column for them
node,way   addr:flats   text         phstore
node,way   aeroway      text         phstore
node,way   amenity      text         phstore
node,way   boundary     text         phstore
node,way   building     text         phstore
node,way   historic     text         phstore
node,way   golf         text         phstore
node,way   landuse      text         phstore
node,way   leisure      text         phstore
node,way   man_made     text         phstore
node,way   military     text         phstore
node,way   natural      text         phstore
node,way   place        text         phstore
node,way   power        text         phstore
node,way   railway      text         phstore
node,way   shop         text         phstore
node,way   sport        text         phstore
node,way   tourism      text         phstore
node,way   waterway     text         phstore
```

**Comment by mojodna** [comment]
A better config (that does exactly what we want) is here:
https://github.com/openstreetmap/osm2pgsql/blob/master/empty.style

Thanks @pnorman!

**Comment by mojodna** [comment]
Err, maybe not. That looks like it's for an as-yet unreleased version of `osm2pgsql`, as it ignores the `nocolumn` flag.

**Comment by jflemer-ndp** [comment]
I think `empty.style` will work after `s/nocolumn/phstore/g`.
https://gist.github.com/jflemer-ndp/a8c06d055a9b9604a074

**Comment by pnorman** [comment]
Use the version from whatever version of osm2pgsql you're using

**Comment by jflemer-ndp** [comment]
Switched back from `empty` db style to the default OSM db style for osm2pgsql.  This can be adjusted in a local settings file, e.g.:
```
osm2pg_style="https://raw.githubusercontent.com/openstreetmap/osm2pgsql/0.88.1/empty.style"
osm2pg_opt="--create --hstore-all --hstore-add-index --extra-attributes --slim --drop --unlogged"
```
