### ISSUE TITLE
Instructions for creating OMKServer manifest.json files is missing from STEPS.md

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#70]
We were trying to provision phones using the OMK provisioning UI but it wasn't pulling .osm and MBTiles contents, presumably because we weren't including them in the file. Neither of the examples include them.

**Comment by hallahan** [comment]
OpenMapKit Server issue. Putting the osm and mbtiles files in the same directory as the manifest.json in public/deployments/form_name works. Probably we need better instructions?
