### ISSUE TITLE
USB installer breaks HDMI 

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#71]
When doing the POSM build from the Auto-Build USB method, HDMI output drops out at some point. I'm not sure where exactly, however, when I plug in via VGA, I once again get output.

**Comment by mojodna** [comment]
I think this is actually a faulty idle timeout on the HDMI output--I've seen it when tailing logs on the console. Oddly, I haven't been able to get it to wake back up by hitting keys or anything.

**Comment by JeremyGrosser** [comment]
I think we need to add "consoleblank=0" to the kernel parameters. That should prevent it from trying to put the display in standby with DPMS. https://www.kernel.org/doc/Documentation/kernel-parameters.txt

**Comment by mojodna** [comment]
Related: https://bugs.freedesktop.org/show_bug.cgi?id=91629

I will try w/ `consoleblank=0` later today.

**Comment by mojodna** [comment]
(Unplugging the HDMI cable and plugging it back in seems to work.)

**Comment by mojodna** [comment]
Actually, so does switching TTYs (⌃⌥F2).

**Comment by mojodna** [comment]
Potentially related: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1492632

Both seem to suggest that using a recent 4.x kernel may help. 4.2.0 is available, though https://bugs.freedesktop.org/show_bug.cgi?id=91629 recommends 4.3+.

@JeremyGrosser I seem to remember you running into wifi problems w/ 4.x, is that correct?

(Obvs. wifi is more important than video.)

**Comment by JeremyGrosser** [comment]
Yeah, I had wifi problems and kernel panics on 4.2.0... 4.3 was released
after I did my testing, so maybe it's fixed there.

**Comment by mojodna** [comment]
4.3 isn't available in any of the deb sources already on the system. Happen to know if a PPA or some other mechanism is the right way to upgrade on 14.04?

I probably won't do anything other than `consoleblank=0` today, but am thinking about this as I look over and watch the NUC bootstrap itself.

**Comment by mojodna** [comment]
Err, looks like we want 4.4 since 4.3 was a short-lived train.

**Comment by JeremyGrosser** [comment]
If it's not packaged, we'll need to build our own... The easiest way is
to download the kernel sources, copy the kconfig from the most recent
Ubuntu kernel, then 'make deb-pkg'.

There are a lot of downsides to trying to maintain our own kernel, so
I'd prefer to stick to one of the Ubuntu ones if at all possible.

**Comment by mojodna** [comment]
http://kernel.ubuntu.com/~kernel-ppa/mainline/ appears to have them, but it doesn't seem to behave like a normal PPA w/r/t `add-apt-repository`. I was also hoping for your opinion about using that.

Definite :-1: on maintaining our own kernel.

**Comment by mojodna** [comment]
`consoleblank=0` appears to work.

@jflemer-ndp / @JeremyGrosser can you sanity check https://github.com/AmericanRedCross/posm-build/commit/a0bfacca0d445b67f85faedc0d19e99d1d226c48 for me?

**Comment by mojodna** [comment]
Confirmed.

(`cat /proc/cmdline` after boot)
