### ISSUE TITLE
[posm-build] VGA output is not aligned & flickers

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#72]
After my HDMI stops working during Auto-Build, I plug in VGA. It shows up, but then at some point it starts flickering and the VGA output no longer fits the screen.

![bad-align](https://cloud.githubusercontent.com/assets/556367/13063070/328837e0-d3f9-11e5-9545-f9b10a62ee9c.jpg)

Even when I tweak the vertical alignment of my monitor, the lowest line and curser are cut out.

![even-vertical-align](https://cloud.githubusercontent.com/assets/556367/13063080/41e054a2-d3f9-11e5-9ca4-6b8ea079f56d.jpg)

**Comment by mojodna** [comment]
I've seen the flickering when plugged into HDMI, but it's gone away after rebooting with the kernel installed by `wifi`.

**Comment by hallahan** [comment]
Doesn't seem to be a problem when installing a second time fresh. I'll close, reopen if it happens again.
