### ISSUE TITLE
Locally rendered tiles fail when following STEPS.md

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#74]
I'm working through [STEPS.md](https://github.com/AmericanRedCross/posm/blob/53f4815093ae9c9e1372438f0953871358fd81fb/STEPS.md#restart-tile-server), and after restarting the tile server, I'm able to view pre-fetched OSM MBTiles fine and dandy, but the `mm` locally rendered tiles fail.

https://github.com/AmericanRedCross/posm/blob/53f4815093ae9c9e1372438f0953871358fd81fb/STEPS.md#restart-tile-server

<img width="1013" alt="screenshot 2016-02-17 06 38 51" src="https://cloud.githubusercontent.com/assets/556367/13112789/39f264bc-d541-11e5-8f17-744668ad0677.png">

Looking at  `index.json`, I get some useful information about our problem:

<img width="666" alt="screenshot 2016-02-17 06 39 08" src="https://cloud.githubusercontent.com/assets/556367/13112813/4d88197c-d541-11e5-804a-1f1e816c1b05.png">

Where do we find `project.xml`, and when should we place it in `/opt/gis/project.xml`?

cc/ @mojodna

**Comment by dalekunce** [comment]
did you edit the tesserra config?

**Comment by hallahan** [comment]
Wrong path to `project.xml`. Fixed instructions:

https://github.com/AmericanRedCross/posm/commit/2df9a4e2a98be87d167f975b4f4656b541308ff3
