### ISSUE TITLE
POSM iD does not initialize

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#75]
After executing posm-build in an Ubuntu VM, iD is not initializing.

<img width="1410" alt="screenshot 2016-02-17 07 32 41" src="https://cloud.githubusercontent.com/assets/556367/13114901/698488c8-d54a-11e5-8240-891e248dc217.png">

Apparently no `id.ui` object exits.

<img width="114" alt="screenshot 2016-02-17 07 39 18" src="https://cloud.githubusercontent.com/assets/556367/13114741/a8863f54-d549-11e5-874c-df030c823c13.png">

I'm not sure why it doesn't exist, when it does indeed load `js/id/ui.js`. 

<img width="968" alt="screenshot 2016-02-17 07 43 58" src="https://cloud.githubusercontent.com/assets/556367/13114866/3d6fdf30-d54a-11e5-8f94-978b1aad4dd7.png">

OpenMapKit iD has this id.ui function, and so does the master OSM iD. What's going on here?

cc/ @mojodna

**Comment by mojodna** [comment]
`iD` chains methods, but not everything returns the same instance.

You'll need to re-provision `osm` (to generate credentials) and `id` (to pick up the change).

Alternately, you can apply the diff locally.

**Comment by hallahan** [comment]
Maybe one of the function calls in this very long chaining is not returning the right thing. I see that the `id` object doesn't have the same properties as found in the OpenMapKit iD `id` object.

https://github.com/AmericanRedCross/iD/blob/4caf384ed60b027b1f0afc19f08dce1adcc5a180/index.html#L250-L262

POSM iD `id` object:

<img width="486" alt="screenshot 2016-02-17 07 52 00" src="https://cloud.githubusercontent.com/assets/556367/13115118/61169d74-d54b-11e5-9fbc-36fcaa32b450.png">

OpenMapKit iD `id` object:

<img width="413" alt="screenshot 2016-02-17 07 53 11" src="https://cloud.githubusercontent.com/assets/556367/13115151/87407dda-d54b-11e5-89e6-d81bef82062f.png">
