### ISSUE TITLE
Change default tiles in OSM

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#79]
Current tiles pull from tile.openstreetmap.org, so they a) depend on an external network and b) don't represent the current state of edits.

Alas, this isn't as easy as one would hope, as the OSM website uses a bunch of custom Leaflet layers with hard-coded URL templates.

**Comment by mojodna** [comment]
(We almost certainly want to use posm-carto for this purpose.)

**Comment by almccon** [comment]
Although it would also be nice to render openstreetmap-carto tiles locally, which should be possible, since posm-carto uses the same database schema.

**Comment by mojodna** [comment]
@jflemer-ndp has this largely working already, though it isn't wired up by default. We'd talked about switching from the openstreetmap-style Debian packages to deploying `openstreetmap-carto` in the same way as `posm-carto`.

**Comment by mojodna** [comment]
@jflemer-ndp notes that we can use the captive portal configuration to force these to be loaded from elsewhere if it turns out that it's too difficult to make changes to openstreetmap-website.
