### ISSUE TITLE
NUC-as-AP only supports one client at a time (phones excluded)

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#80]
While talking to @dalekunce last week, he mentioned that ARC staff were only able to connect one laptop at a time to the wifi with any others "timing out" (connecting to wifi, not DHCP, from what I understood). They were, however, able to connect all (?) of the phones during this period.

@JeremyGrosser please investigate if you're able. Coordinate with @jharpster for a field test in the SpatialDev office.

Our supported device target should probably be ~20 (though higher would be nice).

/cc @jflemer-ndp

**Comment by JeremyGrosser** [comment]
Were all the laptops macs?

**Comment by mojodna** [comment]
Likely yes, but @dalekunce should confirm.

**Comment by dalekunce** [comment]
yes

**Comment by mojodna** [comment]
@JeremyGrosser any luck?

Related: have you been able to coordinate w/ @jharpster on a smoke test w/ lots of devices at the SpatialDev office?

**Comment by JeremyGrosser** [comment]
I haven't been able to reproduce the problem yet, was planning on taking another stab at it this evening.

I haven't planned a time to do a smoke test because I want to figure this issue out before I waste a bunch of people's time.

**Comment by mojodna** [comment]
Makes sense.

**Comment by mojodna** [comment]
Closed in favor of #84.
