### ISSUE TITLE
POSM iD doesnt let me log in

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#81]
Troubleshoot why the auth popup is blank. I can't log in and save my changes to the POSM OSM API.

<img width="1410" alt="screenshot 2016-02-17 09 01 29" src="https://cloud.githubusercontent.com/assets/556367/13117508/10a836fe-d555-11e5-9ea3-0ba67c7335f8.png">

**Comment by hallahan** [comment]
On the regular iD, when pressing save, we hit the oauth library, which in turn fires a popup and requests a POST as such:

http://www.openstreetmap.org/oauth/request_token

![screenshot 2016-02-17 09 53 31](https://cloud.githubusercontent.com/assets/556367/13119169/8f027666-d55c-11e5-8c9b-a83a8410e387.png)

On POSM iD, when pressing save, oauth does a post to:

http://posm.local/osm/oauth/request_token

Oh darn, we get a 500!

![screenshot 2016-02-17 09 58 53](https://cloud.githubusercontent.com/assets/556367/13119254/125c2eb2-d55d-11e5-8819-c629fe4ccc73.png)

Gee, what is RoR telling us is the reason?

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<body>
  <img src="/assets/osm_logo.png" style="float:left; margin:10px">
  <div style="float:left;">
    <h1>Application error</h1>
    <p>The OpenStreetMap server encountered an unexpected condition that prevented it from fulfilling the request (HTTP 500)</p>
    <p>Feel free to <a href="http://wiki.openstreetmap.org/wiki/Contact" title="Various contact channels explained">contact</a> the OpenStreetMap community if your problem persists. Make a note of the exact URL / post data of your request.</p>
    <p>This may be a problem in our Ruby On Rails code. 500 occurs with exceptions thrown outside of an action (like in Dispatcher setups or broken Ruby code)</p>
  </div>
</body>
</html>
```

Nothing very informative...

At least we know we're getting through NGINX to RoR. How would we debug this in RoR?

**Comment by hallahan** [comment]
I'm noticing that the real OSM endpoint doesn't have the `/osm` prefix. Could it be that a totally different web service is handling oauth?

cc/ @mojodna

**Comment by mojodna** [comment]
`osm-web` is handling OAuth for both.

Check in `/var/logs/osm-web.log` for the stack trace corresponding to the 500. `RAILS_ENV=production` prevents them from from being output to users.

**Comment by hallahan** [comment]
```
Started POST "/osm/oauth/request_token" for 127.0.0.1 at 2016-02-16 20:38:11 -0800
Processing by OauthController#request_token as */*
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `create_request_token' for nil:NilClass):
  config/initializers/cors.rb:9:in `call'
```

**Comment by hallahan** [comment]
You think it's the `/osm` prefix?

**Comment by hallahan** [comment]
Here is the request_token path on the RoR app:

https://github.com/openstreetmap/openstreetmap-website/blob/36cbda3c80beac9496316389d4f082383ed4322a/config/routes.rb#L278

**Comment by mojodna** [comment]
No.

`create_request_token` is a method on `ClientApplication` (https://github.com/americanredcross/openstreetmap-website/blob/77c25dca8c9b60c2fd8dae6eeee1405ec24edf27/app/models/client_application.rb#L46), which means that the expected `ClientApplication` is actually `nil`.

Is that all there is to the stack trace? I'd like to figure out where it's trying to load the app from and figure out why it's coming back as `nil`.

**Comment by hallahan** [comment]
That's all we got regarding errors in the log.

**Comment by mojodna** [comment]
If we automatically log all users in w/ the same username (per #77), this becomes moot. Probably still want to figure out what's going on though.

**Comment by mojodna** [comment]
With #76 implemented, I'm going to call this irrelevant and re-prioritize effort toward #78.
