### ISSUE TITLE
POSM does not set up wifi on firstboot

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm#82]
POSM is still not setting up wifi on the first boot. I have to complete the entire installation and restart to get to the hotspot.

```
root@posm:~# cat posm-firstboot.log 
[Mon Feb 22 20:35:58 2016] Starting: posm firstboot
```

Looking at the bootstrap.log, wifi is done with the rest of the install...

cc/ @jflemer-ndp

**Comment by jflemer-ndp** [comment]
What git hash version was this with?

**Comment by hallahan** [comment]
24180cbabdbba5cb77cbc4d614b41ad789df3a95

**Comment by mojodna** [comment]
Can't reproduce this with latest USB installer + posm-build (which reboots twice). Leaving open for @hallahan to confirm and close.
