### ISSUE TITLE
Configure openstreetmap-website center point

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#87]
Currently defaults to the UK. This involves both configuring it in `posm-build` and determining how it's configured in `openstreetmap-website`.

**Comment by mojodna** [comment]
The best way for `openstreetmap-website` is to set `home_lat`, `home_lon`, and `home_zoom` on the object returned by `User.find_by_display_name("POSM")`, as all users are automatically logged in as POSM.

Since auth is automatically passed, it may be possible to do this using the API, in which case it could be a `curl` request rather than needing to write a Rake task or Ruby script.

**Comment by mojodna** [comment]
API is a no-go, as the only user methods are preferences (which don't include home locations).

**Comment by mojodna** [comment]
```bash
lat=$(jq -r '(.bbox[1] + .bbox[3]) / 2' $manifest_path)
lng=$(jq -r '(.bbox[0] + .bbox[2]) / 2' $manifest_path)
zoom=15

# set POSM's home location
PGHOST="localhost"
PGUSER=$(jq -r .osm_pg_owner /etc/posm.json)
PGPASSWORD=$(jq -r .osm_pg_pass /etc/posm.json)
PGDATABASE=$(jq -r .osm_pg_dbname /etc/posm.json)

psql -c "update users set home_zoom=${zoom}, home_lat=${lat}, home_lon=${lng} where display_name='POSM'"
```

**Comment by hallahan** [comment]
When I set the `users` table like above with the following:

```
psql -c "update users set home_zoom=5, home_lat=39.147, home_lon=-119.399 where display_name='POSM'"
```

It sets up the home lat/lng, but it does not change the initial zoom. The initial zoom is always 10. Some bug... Is this because of something we did?

When in incognito mode and I go to http://osm.posm.io I wind up at

http://osm.posm.io/#map=10/39.1470/-119.3990&layers=P

**Comment by hallahan** [comment]
Also, there is client-side JS that overrides the home location for the user. When you go back to http://osm.posm.io, it starts in the location we were at last, over-riding the user home. I'm poking about looking for where this happens. Thinking about how this should be handled...

**Comment by hallahan** [comment]
The browser's center point gets stored in cookies

```
document.cookie
"_ga=GA1.2.1916835025.1462835068; _osm_location=-119.465%7C39.445%7C6%7CP"
```

**Comment by hallahan** [comment]
Here is where openstreetmap-website sets the cookie:

https://github.com/openstreetmap/openstreetmap-website/blob/38180c56c9be9d99406c9088b60f5912c2648a04/app/assets/javascripts/index.js#L164-L165

**Comment by hallahan** [comment]
It reads the cookie here:

https://github.com/openstreetmap/openstreetmap-website/blob/38180c56c9be9d99406c9088b60f5912c2648a04/app/assets/javascripts/osm.js.erb#L109-L113

**Comment by hallahan** [comment]
In specific, here's the answer to my issue about the map defaulting to the zoom of 10. It's a hard coded thing client side that ignores what the server wants:

```js
    } else if (loc = $.cookie('_osm_location')) {
      loc = loc.split("|");
      mapParams.lon = parseFloat(loc[0]);
      mapParams.lat = parseFloat(loc[1]);
      mapParams.zoom = parseInt(loc[2]);
    } else if (OSM.home) {
      mapParams.lon = OSM.home.lon;
      mapParams.lat = OSM.home.lat;
      mapParams.zoom = 10;
```
