### ISSUE TITLE
Host AP mode

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#9]
The NUC should be configured such that it broadcasts a wireless network that can be joined by nearby devices. SSID and password should be configurable, as we'll want to be able to change it from a web UI at some point.

**Comment by mojodna** [comment]
The AP should not be open; encrypted connections should be used.

**Comment by jflemer-ndp** [comment]
Host AP mode has been implemented, web management of Host AP mode and captive portal is not.
