### ISSUE TITLE
Automate cloud data gathering

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#93]
https://github.com/AmericanRedCross/posm/blob/master/STEPS.md#initial-data-gathering-cloud

Adapt the [HOT Export Tool](http://export.hotosm.org/en/) ([GitHub](https://github.com/hotosm/osm-export-tool2)) for this purpose by modifying the data initial data collected and adding new tasks to fetch additional data sources.

**Comment by dalekunce** [comment]
@mojodna would we want to just configure the HOT export tool to do all of this for us and submit it as a PR to master or are you seeing this as a fork of that tool with limited ability to push features back up?

**Comment by mojodna** [comment]
Relatively independent fork initially, but ideally to push as much back up as possible. (Same approach for openstreetmap-website--there are some changes we're making that are more generally appropriate.)

**Comment by mojodna** [comment]
I'm having good luck doing this as PR-able chunks so far:

* https://github.com/hotosm/osm-export-tool2/pull/114
* https://github.com/hotosm/osm-export-tool2/pull/115
* https://github.com/hotosm/osm-export-tool2/pull/116
* https://github.com/hotosm/osm-export-tool2/pull/117

**Comment by dalekunce** [comment]
Love the progress and the fact that we can, thus far, push all of this back upstream.

cc @mataharimhairi

**Comment by mojodna** [comment]
Live!

http://ec2-52-32-62-7.us-west-2.compute.amazonaws.com/

Upstreaming the MBTiles creation is a little questionable, as the amount of time it takes to generate archives has the potential to back up the queues. I'll think on that and see if there's a better way we can do it.
