### ISSUE TITLE
Display survey area boundaries in OMK Android

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#94]
(Where survey area boundaries correspond to the area covered by each page in a Field Papers atlas.)

@hallahan what sort of options do we have for displaying this in OMK?

GeoJSON would be the obvious format to provide it in, but that assumes that you can display a raster background (from MBTiles), OSM XML, **and** a GeoJSON layer somewhere in the mix.

I could also provide a second MBTiles archive w/ boundaries (as transparent rasters)--does OMK support stacked backgrounds?

Alternately, I could imagine creating a derivative MBTiles archive w/ boundaries stamped into whatever you would be using as the background imagery. This is probably the least-clean option, but it's a possibility.

/cc @DrishT @dalekunce

**Comment by hallahan** [comment]
I ​_think_​ stacked raster layers work.

GeoJSON performs so poorly on the renderer, that it will bring the app to it's knees with only a few vertices -- no go.

OSM XML could work. I could probably hack it to draw the boundaries in a different color. However, you wouldn't have a label.

MBTiles I like. Even if it's transparent PNGs for now, when we have a vector tile based mapping lib (MapboxGL), switching that process to vector tiles will be easy.

**Comment by mojodna** [comment]
1. @hallahan to determine the best format for OMK to consume.
2. @mojodna to provide some sample data in that format from FP to test with.
3. @hallahan and @mojodna to close the loop and make it live.

**Comment by dalekunce** [comment]
I vote for mbtiles so we can quickly restyle them however we want *and* have labels.

**Comment by mojodna** [comment]
Additional context:

> If we could do that it would increase the quality of the data as volunteers have an extra way to verify where they are. GPS works but is not always reliable. Our volunteers don’t always speak english and map literally is quiet a challenge for most so having those boundaries on the phone match the field papers would be great. We did it on the Garmin 64 GPS but not sure how it would work with openmapkit?

**Comment by hallahan** [comment]
Done, should have been an OpenMapKit Android Issue (which it was)
